QBShared = QBShared or {}
QBShared.VehicleHashes = {}

QBShared.Vehicles = {
	-- X CLASS
	['bdivo'] = {							
		['name'] = 'Divo',
		['brand'] = 'Bugatti',
		['model'] = 'bdivo',
		['price'] = 3500000,
		['category'] = 'Bugatti',
		['hash'] = `bdivo`,
		['shop'] = 'luxury',
     },
	 ['DevGambit_VeyronTT'] = {							
		['name'] = 'Veyron TT',
		['brand'] = 'Bugatti',
		['model'] = 'DevGambit_VeyronTT',
		['price'] = 3000000,
		['category'] = 'Supporter',
		['hash'] = `DevGambit_VeyronTT`,
		['shop'] = 'Supporter',
     },
	 ['DevGambit_812Stallone'] = {							
		['name'] = '812s',
		['brand'] = 'Ferrari',
		['model'] = 'DevGambit_812Stallone',
		['price'] = 2000000,
		['category'] = 'Supporter',
		['hash'] = `DevGambit_812Stallone`,
		['shop'] = 'Supporter',
     },
	 ['agerars'] = {							
		['name'] = 'Agera RS',
		['brand'] = 'Koenigsegg',
		['model'] = 'agerars',
		['price'] = 3300000,
		['category'] = 'Koenigsegg',
		['hash'] = `agerars`,
		['shop'] = 'luxury',
     },
	 ['p1gtr'] = {							
		['name'] = 'P1 GTR',
		['brand'] = 'Mclaren',
		['model'] = 'p1gtr',
		['price'] = 22000000,
		['category'] = 'Supporter',
		['hash'] = `p1gtr`,
		['shop'] = 'Supporter',
     },
	 ['senna'] = {							
		['name'] = 'Senna',
		['brand'] = 'Mclaren',
		['model'] = 'senna',
		['price'] = 2100000,
		['category'] = 'Supporter',
		['hash'] = `senna`,
		['shop'] = 'Supporter',
     },
	 ['huayrar'] = {							
		['name'] = 'Huayra - R',
		['brand'] = 'Pagani',
		['model'] = 'huayrar',
		['price'] = 2200000,
		['category'] = 'Supporter',
		['hash'] = `huayrar`,
		['shop'] = 'Supporter',
     },
	 ['zondac'] = {							
		['name'] = 'Zonda C',
		['brand'] = 'Pagani',
		['model'] = 'zondac',
		['price'] = 2400000,
		['category'] = 'Pagani',
		['hash'] = `zondac`,
		['shop'] = 'luxury',
     },
	 -- VANILLA XCLASS
	 ['ENTITY2'] = {							
		['name'] = 'Entity',
		['brand'] = 'TIBUS',
		['model'] = 'ENTITY2',
		['price'] = 2230000,
		['category'] = 'XClass',
		['hash'] = `ENTITY2`,
		['shop'] = 'luxury',
     },
	 ['TAIPAN'] = {							
		['name'] = 'TAIPAN',
		['brand'] = 'TIBUS',
		['model'] = 'TAIPAN',
		['price'] = 2675000,
		['category'] = 'XClass',
		['hash'] = `TAIPAN`,
		['shop'] = 'luxury',
     },
	 ['TYRANT'] = {							
		['name'] = 'TYRANT',
		['brand'] = 'TIBUS',
		['model'] = 'TYRANT',
		['price'] = 2250000,
		['category'] = 'XClass',
		['hash'] = `TYRANT`,
		['shop'] = 'luxury',
     },
	 ['DEVESTE'] = {							
		['name'] = 'DEVESTE',
		['brand'] = 'TIBUS',
		['model'] = 'DEVESTE',
		['price'] = 2550000,
		['category'] = 'XClass',
		['hash'] = `DEVESTE`,
		['shop'] = 'luxury',
     },
	 ['PROTOTIPO'] = {							
		['name'] = 'PROTOTIPO',
		['brand'] = 'TIBUS',
		['model'] = 'PROTOTIPO',
		['price'] = 2750000,
		['category'] = 'XClass',
		['hash'] = `PROTOTIPO`,
		['shop'] = 'luxury',
     },
	 ['FMJ'] = {							
		['name'] = 'FMJ',
		['brand'] = 'TIBUS',
		['model'] = 'FMJ',
		['price'] = 2350000,
		['category'] = 'XClass',
		['hash'] = `FMJ`,
		['shop'] = 'luxury',
     },
	 ['VAGNER'] = {							
		['name'] = 'VAGNER',
		['brand'] = 'TIBUS',
		['model'] = 'VAGNER',
		['price'] = 2200000,
		['category'] = 'XClass',
		['hash'] = `VAGNER`,
		['shop'] = 'luxury',
     },
	 ['NERO2'] = {							
		['name'] = 'NERO',
		['brand'] = 'TIBUS',
		['model'] = 'NERO2',
		['price'] = 2350000,
		['category'] = 'XClass',
		['hash'] = `NERO2`,
		['shop'] = 'luxury',
     },
	 ['VISIONE'] = {							
		['name'] = 'VISIONE',
		['brand'] = 'TIBUS',
		['model'] = 'VISIONE',
		['price'] = 2150000,
		['category'] = 'XClass',
		['hash'] = `VISIONE`,
		['shop'] = 'luxury',
     },
	 ['EMERUS'] = {							
		['name'] = 'EMERUS',
		['brand'] = 'TIBUS',
		['model'] = 'EMERUS',
		['price'] = 2050000,
		['category'] = 'XClass',
		['hash'] = `EMERUS`,
		['shop'] = 'luxury',
     },
	 ['THRAX'] = {							
		['name'] = 'THRAX',
		['brand'] = 'TIBUS',
		['model'] = 'THRAX',
		['price'] = 2400000,
		['category'] = 'XClass',
		['hash'] = `THRAX`,
		['shop'] = 'luxury',
     },
	-- S CLASS
	['ast'] = {							
		['name'] = 'Vanquish',
		['brand'] = 'Astonmartin',
		['model'] = 'ast',
		['price'] = 700000,
		['category'] = 'Astonmartin',
		['hash'] = `ast`,
		['shop'] = 'luxury',
     },
	 ['r820'] = {							
		['name'] = 'R8',
		['brand'] = 'Audi',
		['model'] = 'r820',
		['price'] = 805000,
		['category'] = 'Audi',
		['hash'] = `r820`,
		['shop'] = 'luxury',
     },
	 ['mansm8'] = {							
		['name'] = 'Mansaug M8',
		['brand'] = 'BMW',
		['model'] = 'mansm8',
		['price'] = 610000,
		['category'] = 'Supporter',
		['hash'] = `mansm8`,
		['shop'] = 'Supporter',
     },
	 
	 ['mansc8'] = {							
		['name'] = 'Mansaug C8',
		['brand'] = 'Chevrolet',
		['model'] = 'mansc8',
		['price'] = 680000,
		['category'] = 'Supporter',
		['hash'] = `mansc8`,
		['shop'] = 'Supporter',
     },
	 ['shellephant'] = {							
		['name'] = 'Hellephant',
		['brand'] = 'Chrysler',
		['model'] = 'shellephant',
		['price'] = 700000,
		['category'] = 'Supporter',
		['hash'] = `shellephant`,
		['shop'] = 'Supporter',
     },
	 ['c4viperwb'] = {							
		['name'] = 'Viper Widebody',
		['brand'] = 'Dodge',
		['model'] = 'c4viperwb',
		['price'] = 755000,
		['category'] = 'Dodge',
		['hash'] = `c4viperwb`,
		['shop'] = 'luxury',
     },
	 
	 ["gwopdemon"] = {
		["name"] = "Demon",
		["brand"] = "Dodge",
		["model"] = "gwopdemon",
		["price"] = 680000,
		["category"] = "Supporter",
		["hash"] = `gwopdemon`,
		["shop"] = "Supporter",
	},
	['488'] = {							
		['name'] = '488 C',
		['brand'] = 'Ferrari',
		['model'] = '488',
		['price'] = 825000,
		['category'] = 'Supporter',
		['hash'] = `488`,
		['shop'] = 'Supporter',
     },
	 ['f430s'] = {							
		['name'] = 'F430s',
		['brand'] = 'Ferrari',
		['model'] = 'f430s',
		['price'] = 700000,
		['category'] = 'Ferrari',
		['hash'] = `f430s`,
		['shop'] = 'luxury',
     },
	 ['f458'] = {							
		['name'] = '458',
		['brand'] = 'Ferrari',
		['model'] = 'f458',
		['price'] = 950000,
		['category'] = 'Ferrari',
		['hash'] = `f458`,
		['shop'] = 'luxury',
     },
	 ['forgt50020'] = {							
		['name'] = 'GT500',
		['brand'] = 'Ford',
		['model'] = 'forgt50020',
		['price'] = 620000,
		['category'] = 'Supporter',
		['hash'] = `forgt50020`,
		['shop'] = 'Supporter',
     },
	 ['lfa'] = {							
		['name'] = 'LFA',
		['brand'] = 'Lexus',
		['model'] = 'lfa',
		['price'] = 600000,
		['category'] = 'Lexus',
		['hash'] = `lfa`,
		['shop'] = 'luxury',
     }, 
	 ['18performante'] = {							
		['name'] = 'Huracan Performante',
		['brand'] = 'Lamborghini',
		['model'] = '18performante',
		['price'] = 950000,
		['category'] = 'Lamborghini',
		['hash'] = `18performante`,
		['shop'] = 'luxury',
     },
	 ['hevo'] = {							
		['name'] = 'Evo Spyder',
		['brand'] = 'Lamborghini',
		['model'] = 'hevo',
		['price'] = 900000,
		['category'] = 'Supporter',
		['hash'] = `hevo`,
		['shop'] = 'Supporter',
     },
	 ['lp610'] = {							
		['name'] = 'Huracan LP610',
		['brand'] = 'Lamborghini',
		['model'] = 'lp610',
		['price'] = 925000,
		['category'] = 'Lamborghini',
		['hash'] = `lp610`,
		['shop'] = 'luxury',
     },
	 ['lp700'] = {							
		['name'] = 'Aventador LP700',
		['brand'] = 'Lamborghini',
		['model'] = 'lp700',
		['price'] = 960000,
		['category'] = 'Supporter',
		['hash'] = `lp700`,
		['shop'] = 'Supporter',
     },
	 ['rmodlp750'] = {							
		['name'] = 'Aventador lp750',
		['brand'] = 'Lamborghini',
		['model'] = 'rmodlp750',
		['price'] = 980000,
		['category'] = 'Lamborghini',
		['hash'] = `rmodlp750`,
		['shop'] = 'luxury',
     },
	 ['675lt'] = {							
		['name'] = '675lt',
		['brand'] = 'Mclaren',
		['model'] = '675lt',
		['price'] = 920000,
		['category'] = 'Mclaren',
		['hash'] = `675lt`,
		['shop'] = 'luxury',
     },
	 ['amggtrr20'] = {							
		['name'] = 'AMG GTR',
		['brand'] = 'Mercedes',
		['model'] = 'amggtrr20',
		['price'] = 800000,
		['category'] = 'Supporter',
		['hash'] = `amggtrr20`,
		['shop'] = 'Supporter',
     },
	 ['r35'] = {							
		['name'] = 'R35 GTR',
		['brand'] = 'Mercedes',
		['model'] = 'r35',
		['price'] = 790000,
		['category'] = 'Supporter',
		['hash'] = `r35`,
		['shop'] = 'Supporter',
     },
	 ['skyline'] = {							
		['name'] = 'R34',
		['brand'] = 'Nissan',
		['model'] = 'skyline',
		['price'] = 650000,
		['category'] = 'Nissan',
		['hash'] = `skyline`,
		['shop'] = 'luxury',
     },
	 ['911r'] = {							
		['name'] = '911R',
		['brand'] = 'Porsche',
		['model'] = '911r',
		['price'] = 750000,
		['category'] = 'Porsche',
		['hash'] = `911r`,
		['shop'] = 'luxury',
     },
	 ['918'] = {							
		['name'] = '918',
		['brand'] = 'Porsche',
		['model'] = '918',
		['price'] = 890000,
		['category'] = 'Supporter',
		['hash'] = `918`,
		['shop'] = 'Supporter',
     },
	 ['pgt3'] = {							
		['name'] = 'GT3RS',
		['brand'] = 'Porsche',
		['model'] = 'pgt3',
		['price'] = 805000,
		['category'] = 'Supporter',
		['hash'] = `pgt3`,
		['shop'] = 'Supporter',
     },
	 ['tesroad20'] = {							
		['name'] = 'Roadster',
		['brand'] = 'Tesla',
		['model'] = 'tesroad20',
		['price'] = 800000,
		['category'] = 'Supporter',
		['hash'] = `tesroad20`,
		['shop'] = 'Supporter',
	 },
	 -- VANILLA SCLASS
	['XA21'] = {							
		['name'] = 'XA21',
		['brand'] = 'TIBUS',
		['model'] = 'XA21',
		['price'] = 800000,
		['category'] = 'SClass',
		['hash'] = `XA21`,
		['shop'] = 'luxury',
     },
	['FURIA'] = {							
		['name'] = 'FURIA',
		['brand'] = 'TIBUS',
		['model'] = 'FURIA',
		['price'] = 675000,
		['category'] = 'SClass',
		['hash'] = `FURIA`,
		['shop'] = 'luxury',
     },

	 ['VACCA'] = {							
		['name'] = 'VACCA',
		['brand'] = 'TIBUS',
		['model'] = 'VACCA',
		['price'] = 587000,
		['category'] = 'SClass',
		['hash'] = `VACCA`,
		['shop'] = 'luxury',
     },
	['REAPER'] = {							
		['name'] = 'REAPER',
		['brand'] = 'TIBUS',
		['model'] = 'REAPER',
		['price'] = 597500,
		['category'] = 'SClass',
		['hash'] = `REAPER`,
		['shop'] = 'luxury',
     },

	 ['ITALIRSX'] = {							
		['name'] = 'ITALI RSX',
		['brand'] = 'TIBUS',
		['model'] = 'ITALIRSX',
		['price'] = 605000,
		['category'] = 'SClass',
		['hash'] = `ITALIRSX`,
		['shop'] = 'luxury',
     },
	['ITALIGTB2'] = {							
		['name'] = 'ITALI GTB',
		['brand'] = 'TIBUS',
		['model'] = 'ITALIGTB2',
		['price'] = 675000,
		['category'] = 'SClass',
		['hash'] = `ITALIGTB2`,
		['shop'] = 'luxury',
     },
	 ['TEMPESTA'] = {							
		['name'] = 'TEMPESTA',
		['brand'] = 'TIBUS',
		['model'] = 'TEMPESTA',
		['price'] = 605000,
		['category'] = 'SClass',
		['hash'] = `TEMPESTA`,
		['shop'] = 'luxury',
     },
	['OSIRIS'] = {							
		['name'] = 'OSIRIS',
		['brand'] = 'TIBUS',
		['model'] = 'OSIRIS',
		['price'] = 587500,
		['category'] = 'SClass',
		['hash'] = `OSIRIS`,
		['shop'] = 'luxury',
     },
	 ['IGNUS'] = {							
		['name'] = 'IGNUS',
		['brand'] = 'TIBUS',
		['model'] = 'IGNUS',
		['price'] = 535000,
		['category'] = 'SClass',
		['hash'] = `IGNUS`,
		['shop'] = 'luxury',
     },
	['ZENO'] = {							
		['name'] = 'ZENO',
		['brand'] = 'TIBUS',
		['model'] = 'ZENO',
		['price'] = 510000,
		['category'] = 'SClass',
		['hash'] = `ZENO`,
		['shop'] = 'luxury',
     },
	 ['TYRUS'] = {							
		['name'] = 'TYRUS',
		['brand'] = 'TIBUS',
		['model'] = 'TYRUS',
		['price'] = 575000,
		['category'] = 'SClass',
		['hash'] = `TYRUS`,
		['shop'] = 'luxury',
     },
	['TENF2'] = {							
		['name'] = 'NF-GT',
		['brand'] = 'TIBUS',
		['model'] = 'TENF2',
		['price'] = 660000,
		['category'] = 'SClass',
		['hash'] = `TENF2`,
		['shop'] = 'luxury',
     },
	 ['TORERO2'] = {							
		['name'] = 'TORERO',
		['brand'] = 'TIBUS',
		['model'] = 'TORERO2',
		['price'] = 640000,
		['category'] = 'SClass',
		['hash'] = `TORERO2`,
		['shop'] = 'luxury',
     },
	 ['ITALIGTO'] = {							
		['name'] = 'ITALIGTO',
		['brand'] = 'TIBUS',
		['model'] = 'ITALIGTO',
		['price'] = 635000,
		['category'] = 'SClass',
		['hash'] = `ITALIGTO`,
		['shop'] = 'luxury',
     },
	 ['SCHLAGEN'] = {							
		['name'] = 'SCHLAGEN',
		['brand'] = 'TIBUS',
		['model'] = 'SCHLAGEN',
		['price'] = 522000,
		['category'] = 'SClass',
		['hash'] = `SCHLAGEN`,
		['shop'] = 'luxury',
     },
	 ['pfister811'] = {							
		['name'] = '811',
		['brand'] = 'TIBUS',
		['model'] = 'pfister811',
		['price'] = 563000,
		['category'] = 'SClass',
		['hash'] = `pfister811`,
		['shop'] = 'luxury',
     },
	 ['CYCLONE'] = {							
		['name'] = 'CYCLONE',
		['brand'] = 'TIBUS',
		['model'] = 'CYCLONE',
		['price'] = 575000,
		['category'] = 'SClass',
		['hash'] = `CYCLONE`,
		['shop'] = 'luxury',
     },
	 ['INFERNUS2'] = {							
		['name'] = 'INFERNUS',
		['brand'] = 'TIBUS',
		['model'] = 'INFERNUS2',
		['price'] = 535000,
		['category'] = 'SClass',
		['hash'] = `INFERNUS2`,
		['shop'] = 'luxury',
     },
	 ['COQUETTE4'] = {							
		['name'] = 'COQUETTE',
		['brand'] = 'TIBUS',
		['model'] = 'COQUETTE4',
		['price'] = 575000,
		['category'] = 'SClass',
		['hash'] = `COQUETTE4`,
		['shop'] = 'luxury',
     },
	 ['ZORRUSSO'] = {							
		['name'] = 'ZORRUSSO',
		['brand'] = 'TIBUS',
		['model'] = 'ZORRUSSO',
		['price'] = 585000,
		['category'] = 'SClass',
		['hash'] = `ZORRUSSO`,
		['shop'] = 'luxury',
     },
	 ['CORSITA'] = {							
		['name'] = 'CORSITA',
		['brand'] = 'TIBUS',
		['model'] = 'CORSITA',
		['price'] = 543000,
		['category'] = 'SClass',
		['hash'] = `CORSITA`,
		['shop'] = 'luxury',
     },
	 
	 -- ACLASS
	 ['ocnetrongt'] = {							
		['name'] = 'E-Tron',
		['brand'] = 'Audi',
		['model'] = 'ocnetrongt',
		['price'] = 380000,
		['category'] = 'Audi',
		['hash'] = `ocnetrongt`,
		['shop'] = 'luxury',
     },
	 
	 
	 ['contss18'] = {							
		['name'] = 'Continental GTSS',
		['brand'] = 'Bentley',
		['model'] = 'contss18',
		['price'] = 505000,
		['category'] = 'Supporter',
		['hash'] = `contss18`,
		['shop'] = 'Supporter',
     },
	 ['e36rb'] = {							
		['name'] = 'E36',
		['brand'] = 'BMW',
		['model'] = 'e36rb',
		['price'] = 350000,
		['category'] = 'BMW',
		['hash'] = `e36rb`,
		['shop'] = 'luxury',
     },
	 ['m5f90'] = {							
		['name'] = 'M5 F90',
		['brand'] = 'BMW',
		['model'] = 'm5f90',
		['price'] = 355000,
		['category'] = 'BMW',
		['hash'] = `m5f90`,
		['shop'] = 'luxury',
     },
	 ['m6prior'] = {							
		['name'] = 'M6 Prior',
		['brand'] = 'BMW',
		['model'] = 'm6prior',
		['price'] = 400000,
		['category'] = 'Supporter',
		['hash'] = `m6prior`,
		['shop'] = 'Supporter',
     },
	 
	 ['z4alchemist'] = {							
		['name'] = 'Z4 Alchemist',
		['brand'] = 'BMW',
		['model'] = 'z4alchemist',
		['price'] = 360000,
		['category'] = 'BMW',
		['hash'] = `z4alchemist`,
		['shop'] = 'luxury',
     },
	 ['brabus850'] = {							
		['name'] = '850',
		['brand'] = 'Brabus',
		['model'] = 'brabus850',
		['price'] = 545000,
		['category'] = 'Brabus',
		['hash'] = `brabus850`,
		['shop'] = 'luxury',
     },
	 ['ctsv16'] = {							
		['name'] = 'CTSV',
		['brand'] = 'Cadillac',
		['model'] = 'ctsv16',
		['price'] = 410000,
		['category'] = 'Cadillac',
		['hash'] = `ctsv16`,
		['shop'] = 'luxury',
     },
	 ['papiss17'] = {							
		['name'] = 'SS',
		['brand'] = 'Chevrolet',
		['model'] = 'papiss17',
		['price'] = 345000,
		['category'] = 'Chevrolet',
		['hash'] = `papiss17`,
		['shop'] = 'luxury',
     },
	 ['300chellcat'] = {							
		['name'] = '300 Hellcat',
		['brand'] = 'Chrysler',
		['model'] = '300chellcat',
		['price'] = 560000,
		['category'] = 'Chrysler',
		['hash'] = `300chellcat`,
		['shop'] = 'luxury',
     },
	 ['scatpack'] = {							
		['name'] = 'Charger Scatpack Widebody',
		['brand'] = 'Dodge',
		['model'] = 'scatpack',
		['price'] = 400000,
		['category'] = 'Dodge',
		['hash'] = `scatpack`,
		['shop'] = 'luxury',
     },
	 ["hellephantdurango"] = {
		["name"] = "Hellephant Durango",
		["brand"] = "Dodge",
		["model"] = "hellephantdurango",
		["price"] = 550000,
		["category"] = "Supporter",
		["hash"] = `hellephantdurango`,
		["shop"] = "Supporter",
	},
	['focusrs'] = {							
		['name'] = 'Focus RS',
		['brand'] = 'Ford',
		['model'] = 'focusrs',
		['price'] = 330000,
		['category'] = 'Ford',
		['hash'] = `focusrs`,
		['shop'] = 'luxury',
     },
	 ['mgt'] = {							
		['name'] = 'Mustang GT',
		['brand'] = 'Ford',
		['model'] = 'mgt',
		['price'] = 350000,
		['category'] = 'Ford',
		['hash'] = `mgt`,
		['shop'] = 'luxury',
     },
	 ['inf'] = {							
		['name'] = 'Q60 Red Sport',
		['brand'] = 'Infiniti',
		['model'] = 'inf',
		['price'] = 350000,
		['category'] = 'Infiniti',
		['hash'] = `inf`,
		['shop'] = 'luxury',
     },
	 ['urus2018'] = {							
		['name'] = 'Urus',
		['brand'] = 'Lamborghini',
		['model'] = 'urus2018',
		['price'] = 590000,
		['category'] = 'Lamborghini',
		['hash'] = `urus2018`,
		['shop'] = 'luxury',
     },
	 
	 ['rcf'] = {							
		['name'] = 'RCF',
		['brand'] = 'Lexus',
		['model'] = 'rcf',
		['price'] = 300000,
		['category'] = 'Lexus',
		['hash'] = `rcf`,
		['shop'] = 'luxury',
     },
	 ['mxpan'] = {							
		['name'] = 'MX5',
		['brand'] = 'Mazda',
		['model'] = 'mxpan',
		['price'] = 305000,
		['category'] = 'Mazda',
		['hash'] = `mxpan`,
		['shop'] = 'luxury',
     },
	 ['rx7veilside'] = {							
		['name'] = 'RX7',
		['brand'] = 'Mazda',
		['model'] = 'rx7veilside',
		['price'] = 335000,
		['category'] = 'Supporter',
		['hash'] = `rx7veilside`,
		['shop'] = 'Supporter',
     },
	 ['a45amg'] = {							
		['name'] = 'A45 AMG',
		['brand'] = 'Mercedes',
		['model'] = 'a45amg',
		['price'] = 355000,
		['category'] = 'Mercedes',
		['hash'] = `a45amg`,
		['shop'] = 'luxury',
     },
	 ['e63sf'] = {							
		['name'] = 'E 63s',
		['brand'] = 'Mercedes',
		['model'] = 'e63sf',
		['price'] = 450000,
		['category'] = 'Mercedes',
		['hash'] = `e63sf`,
		['shop'] = 'luxury',
     },
	 ['mbc63'] = {							
		['name'] = 'c63 AMG',
		['brand'] = 'Mercedes',
		['model'] = 'mbc63',
		['price'] = 420000,
		['category'] = 'Mercedes',
		['hash'] = `mbc63`,
		['shop'] = 'luxury',
     },
	 ['oycmr500'] = {							
		['name'] = 'Rolf Hart',
		['brand'] = 'Mercedes',
		['model'] = 'oycmr500',
		['price'] = 550000,
		['category'] = 'Mercedes',
		['hash'] = `oycmr500`,
		['shop'] = 'luxury',
     },
	 ['992c'] = {							
		['name'] = '992 Carrera S',
		['brand'] = 'Porsche',
		['model'] = '992c',
		['price'] = 400000,
		['category'] = 'Porsche',
		['hash'] = `992c`,
		['shop'] = 'luxury',
     },
	 ['p90d'] = {							
		['name'] = 'Model X P90D',
		['brand'] = 'Tesla',
		['model'] = 'p90d',
		['price'] = 390000,
		['category'] = 'Supporter',
		['hash'] = `p90d`,
		['shop'] = 'Supporter',
     },
	 ['teslapd'] = {							
		['name'] = 'Model S Prior Design',
		['brand'] = 'Tesla',
		['model'] = 'teslapd',
		['price'] = 460000,
		['category'] = 'Supporter',
		['hash'] = `teslapd`,
		['shop'] = 'Supporter',
     },
	 ['trhawk'] = {							
		['name'] = 'Trackhawk',
		['brand'] = 'Jeep',
		['model'] = 'trhawk',
		['price'] = 420000,
		['category'] = 'Jeep',
		['hash'] = `trhawk`,
		['shop'] = 'luxury',
     },
	 ['rmodmi8'] = {							
		['name'] = 'i8',
		['brand'] = 'BMW',
		['model'] = 'rmodmi8',
		['price'] = 380000,
		['category'] = 'Supporter',
		['hash'] = `rmodmi8`,
		['shop'] = 'Supporter',
     },
	 ['211le'] = {							
		['name'] = 'ZL1',
		['brand'] = 'Chevrolet',
		['model'] = '211le',
		['price'] = 495000,
		['category'] = 'Chevrolet',
		['hash'] = `211le`,
		['shop'] = 'luxury',
     },
	 ['c7'] = {							
		['name'] = 'C7',
		['brand'] = 'Chevrolet',
		['model'] = 'c7',
		['price'] = 425000,
		['category'] = 'Chevrolet',
		['hash'] = `c7`,
		['shop'] = 'luxury',
     },
	 ['NixpyCharger21'] = {							
		['name'] = 'Charger Hellcat Widebody',
		['brand'] = 'Dodge',
		['model'] = 'NixpyCharger21',
		['price'] = 500000,
		['category'] = 'Supporter',
		['hash'] = `NixpyCharger21`,
		['shop'] = 'Supporter',
	 },
	 -- VANILLA ACLASS
	 ['banshee2'] = {
		['name'] = 'banshee 900r',
		['brand'] = 'Tibus',
		['model'] = 'banshee2',
		['price'] = 232500,
		['category'] = 'AClass',
		['hash'] = `banshee2`,
		['shop'] = 'luxury',
	},
	['elegy2'] = {
		['name'] = 'Elegy RH8',
		['brand'] = 'Tibus',
		['model'] = 'elegy2',
		['price'] = 225000,
		['category'] = 'AClass',
		['hash'] = `elegy2`,
		['shop'] = 'luxury',
	},
	['ninef'] = {
		['name'] = 'ninef',
		['brand'] = 'Tibus',
		['model'] = 'ninef',
		['price'] = 210000,
		['category'] = 'AClass',
		['hash'] = `ninef`,
		['shop'] = 'luxury',
	},
	['neon'] = {
		['name'] = 'Neon',
		['brand'] = 'Tibus',
		['model'] = 'neon',
		['price'] = 245000,
		['category'] = 'AClass',
		['hash'] = `neon`,
		['shop'] = 'luxury',
	},
	['pariah'] = {
		['name'] = 'pariah',
		['brand'] = 'Tibus',
		['model'] = 'pariah',
		['price'] = 250000,
		['category'] = 'AClass',
		['hash'] = `pariah`,
		['shop'] = 'luxury',
	},
	['seven70'] = {
		['name'] = 'seven70',
		['brand'] = 'Tibus',
		['model'] = 'seven70',
		['price'] = 255000,
		['category'] = 'AClass',
		['hash'] = `seven70`,
		['shop'] = 'luxury',
	},
	['bestiagts'] = {
		['name'] = 'bestia gts',
		['brand'] = 'Tibus',
		['model'] = 'bestiagts',
		['price'] = 215000,
		['category'] = 'AClass',
		['hash'] = `bestiagts`,
		['shop'] = 'luxury',
	},
	['cheetah2'] = {
		['name'] = 'cheetah classic',
		['brand'] = 'Tibus',
		['model'] = 'cheetah2',
		['price'] = 250000,
		['category'] = 'AClass',
		['hash'] = `cheetah2`,
		['shop'] = 'luxury',
	},
	['IMORGON'] = {
		['name'] = 'IMORGON',
		['brand'] = 'Tibus',
		['model'] = 'IMORGON',
		['price'] = 223000,
		['category'] = 'AClass',
		['hash'] = `IMORGON`,
		['shop'] = 'luxury',
	},
	['KOMODA'] = {
		['name'] = 'KOMODA',
		['brand'] = 'Tibus',
		['model'] = 'KOMODA',
		['price'] = 215000,
		['category'] = 'AClass',
		['hash'] = `KOMODA`,
		['shop'] = 'luxury',
	},
	['COMET3'] = {
		['name'] = 'Comet Retro Custom',
		['brand'] = 'Tibus',
		['model'] = 'COMET3',
		['price'] = 275000,
		['category'] = 'AClass',
		['hash'] = `COMET3`,
		['shop'] = 'luxury',
	},
	['ELEGY'] = {
		['name'] = 'Elegy',
		['brand'] = 'Tibus',
		['model'] = 'ELEGY',
		['price'] = 195000,
		['category'] = 'AClass',
		['hash'] = `ELEGY`,
		['shop'] = 'luxury',
	},
	['SULTANRS'] = {
		['name'] = 'SULTANRS',
		['brand'] = 'Tibus',
		['model'] = 'SULTANRS',
		['price'] = 230000,
		['category'] = 'AClass',
		['hash'] = `SULTANRS`,
		['shop'] = 'luxury',
	},
	['comet7'] = {
		['name'] = 'Comet S2c',
		['brand'] = 'Tibus',
		['model'] = 'comet7',
		['price'] = 287000,
		['category'] = 'AClass',
		['hash'] = `comet7`,
		['shop'] = 'luxury',
	},
	['turismo2'] = {
		['name'] = 'turismo classic',
		['brand'] = 'Tibus',
		['model'] = 'turismo2',
		['price'] = 255000,
		['category'] = 'AClass',
		['hash'] = `turismo2`,
		['shop'] = 'luxury',
	},
	['lynx'] = {
		['name'] = 'lynx',
		['brand'] = 'Tibus',
		['model'] = 'lynx',
		['price'] = 205000,
		['category'] = 'AClass',
		['hash'] = `lynx`,
		['shop'] = 'luxury',
	},
	['SHEAVA'] = {
		['name'] = 'SHEAVA',
		['brand'] = 'Tibus',
		['model'] = 'SHEAVA',
		['price'] = 213000,
		['category'] = 'AClass',
		['hash'] = `SHEAVA`,
		['shop'] = 'luxury',
	},
	['neo'] = {
		['name'] = 'neo',
		['brand'] = 'Tibus',
		['model'] = 'neo',
		['price'] = 280000,
		['category'] = 'AClass',
		['hash'] = `neo`,
		['shop'] = 'luxury',
	},
	
	-- BCLASS
	['q8prior'] = {
		['name'] = 'Q8 Prior Design',
		['brand'] = 'Audi',
		['model'] = 'q8prior',
		['price'] = 220000,
		['category'] = 'Audi',
		['hash'] = `q8prior`,
		['shop'] = 'luxury',
	},
	['bentaygast'] = {
		['name'] = 'Bentayga',
		['brand'] = 'Bentley',
		['model'] = 'bentaygast',
		['price'] = 300000,
		['category'] = 'Supporter',
		['hash'] = `bentaygast`,
		['shop'] = 'Supporter',
	},
	['lumma750'] = {
		['name'] = 'Lumma 750',
		['brand'] = 'BMW',
		['model'] = 'lumma750',
		['price'] = 250000,
		['category'] = 'BMW',
		['hash'] = `lumma750`,
		['shop'] = 'luxury',
	},
	['m3f80'] = {
		['name'] = 'M3 F80',
		['brand'] = 'BMW',
		['model'] = 'm3f80',
		['price'] = 200000,
		['category'] = 'BMW',
		['hash'] = `m3f80`,
		['shop'] = 'luxury',
	},
	['brabus700'] = {
		['name'] = 'B700',
		['brand'] = 'Brabus',
		['model'] = 'brabus700',
		['price'] = 390000,
		['category'] = 'Brabus',
		['hash'] = `brabus700`,
		['shop'] = 'luxury',
	},
	['dodgetrx'] = {
		['name'] = 'TRX',
		['brand'] = 'Dodge',
		['model'] = 'dodgetrx',
		['price'] = 225000,
		['category'] = 'Supporter',
		['hash'] = `dodgetrx`,
		['shop'] = 'Supporter',
	},
	['dredurango'] = {
		['name'] = '392 Durango',
		['brand'] = 'Dodge',
		['model'] = 'dredurango',
		['price'] = 290000,
		['category'] = 'Dodge',
		['hash'] = `dredurango`,
		['shop'] = 'luxury',
	},
	['19Raptor'] = {
		['name'] = 'Raptor',
		['brand'] = 'Ford',
		['model'] = '19Raptor',
		['price'] = 190000,
		['category'] = 'Ford',
		['hash'] = `19Raptor`,
		['shop'] = 'luxury',
	},
	['velociraptor'] = {
		['name'] = 'Velociraptor',
		['brand'] = 'Ford',
		['model'] = 'velociraptor',
		['price'] = 500000,
		['category'] = 'Ford',
		['hash'] = `velociraptor`,
		['shop'] = 'luxury',
	},
	['wildtrak'] = {
		['name'] = 'Bronco',
		['brand'] = 'Ford',
		['model'] = 'wildtrak',
		['price'] = 150000,
		['category'] = 'Ford',
		['hash'] = `wildtrak`,
		['shop'] = 'luxury',
	},
	['ipl'] = {
		['name'] = 'G37',
		['brand'] = 'Infiniti',
		['model'] = 'ipl',
		['price'] = 205000,
		['category'] = 'Infiniti',
		['hash'] = `ipl`,
		['shop'] = 'luxury',
	},
	['donator_dylan_gladiator'] = {
		['name'] = 'Rubicon',
		['brand'] = 'Jeep',
		['model'] = 'donator_dylan_gladiator',
		['price'] = 180000,
		['category'] = 'Jeep',
		['hash'] = `donator_dylan_gladiator`,
		['shop'] = 'luxury',
	},
	['is350mod'] = {
		['name'] = 'Is350',
		['brand'] = 'Lexus',
		['model'] = 'is350mod',
		['price'] = 190000,
		['category'] = 'Lexus',
		['hash'] = `is350mod`,
		['shop'] = 'luxury',
	},
	['na6'] = {
		['name'] = 'Miata',
		['brand'] = 'Mazda',
		['model'] = 'na6',
		['price'] = 165000,
		['category'] = 'Mazda',
		['hash'] = `na6`,
		['shop'] = 'luxury',
	},
	['benze55'] = {
		['name'] = 'e55',
		['brand'] = 'Mercedes',
		['model'] = 'benze55',
		['price'] = 170000,
		['category'] = 'Mercedes',
		['hash'] = `benze55`,
		['shop'] = 'luxury',
	},
	['gle'] = {
		['name'] = 'GLE',
		['brand'] = 'Mercedes',
		['model'] = 'gle',
		['price'] = 300000,
		['category'] = 'Supporter',
		['hash'] = `gle`,
		['shop'] = 'Supporter',
	},
	['gx370z'] = {
		['name'] = '370z',
		['brand'] = 'Nissan',
		['model'] = 'gx370z',
		['price'] = 213000,
		['category'] = 'Nissan',
		['hash'] = `gx370z`,
		['shop'] = 'luxury',
	},
	['macanpd600m'] = {
		['name'] = 'Macon Prior Design',
		['brand'] = 'Porsche',
		['model'] = 'macanpd600m',
		['price'] = 320000,
		['category'] = 'Supporter',
		['hash'] = `macanpd600m`,
		['shop'] = 'Supporter',
	},
	['pturismo'] = {
		['name'] = 'Panamera',
		['brand'] = 'Porsche',
		['model'] = 'pturismo',
		['price'] = 285000,
		['category'] = 'Porsche',
		['hash'] = `pturismo`,
		['shop'] = 'luxury',
	},
	['rcucullinanbbli'] = {
		['name'] = 'Cullinan',
		['brand'] = 'RollsRoyce',
		['model'] = 'cullinanbb',
		['price'] = 383000,
		['category'] = 'Supporter',
		['hash'] = `cullinanbb`,
		['shop'] = 'Supporter',
	},
	['rrphantom'] = {
		['name'] = 'Phantom',
		['brand'] = 'RollsRoyce',
		['model'] = 'rrphantom',
		['price'] = 375000,
		['category'] = 'RollsRoyce',
		['hash'] = `rrphantom`,
		['shop'] = 'luxury',
	},
	['wraith'] = {
		['name'] = 'Wraith',
		['brand'] = 'RollsRoyce',
		['model'] = 'wraith',
		['price'] = 350000,
		['category'] = 'RollsRoyce',
		['hash'] = `wraith`,
		['shop'] = 'luxury',
	},
	['brztuning'] = {
		['name'] = 'BRZ',
		['brand'] = 'Subaru',
		['model'] = 'brztuning',
		['price'] = 190000,
		['category'] = 'Subaru',
		['hash'] = `brztuning`,
		['shop'] = 'luxury',
	},
	['gt86'] = {
		['name'] = 'GT86',
		['brand'] = 'Toyota',
		['model'] = 'gt86',
		['price'] = 170000,
		['category'] = 'Toyota',
		['hash'] = `gt86`,
		['shop'] = 'luxury',
	},
	-- VANILLA BCLASS
	['DOMINATOR3'] = {
		['name'] = 'DOMINATOR GT',
		['brand'] = 'Tibus',
		['model'] = 'DOMINATOR3',
		['price'] = 83000,
		['category'] = 'BClass',
		['hash'] = `DOMINATOR3`,
		['shop'] = 'luxury',
	},
	['DOMINATOR7'] = {
		['name'] = 'DOMINATOR ACP',
		['brand'] = 'Tibus',
		['model'] = 'DOMINATOR7',
		['price'] = 135000,
		['category'] = 'BClass',
		['hash'] = `DOMINATOR7`,
		['shop'] = 'luxury',
	},
	['BUFFALO4'] = {
		['name'] = 'Buffalo',
		['brand'] = 'Tibus',
		['model'] = 'BUFFALO4',
		['price'] = 95000,
		['category'] = 'BClass',
		['hash'] = `BUFFALO4`,
		['shop'] = 'luxury',
	},
	['RAPIDGT3'] = {
		['name'] = 'Rapid GT',
		['brand'] = 'Tibus',
		['model'] = 'RAPIDGT3',
		['price'] = 68000,
		['category'] = 'BClass',
		['hash'] = `RAPIDGT3`,
		['shop'] = 'luxury',
	},
	['GAUNTLET4'] = {
		['name'] = 'Hellfire',
		['brand'] = 'Tibus',
		['model'] = 'GAUNTLET4',
		['price'] = 125000,
		['category'] = 'BClass',
		['hash'] = `GAUNTLET4`,
		['shop'] = 'luxury',
	},
	['RUINER4'] = {
		['name'] = 'Ruiner',
		['brand'] = 'Tibus',
		['model'] = 'RUINER4',
		['price'] = 63000,
		['category'] = 'BClass',
		['hash'] = `RUINER4`,
		['shop'] = 'luxury',
	},
	['VIGERO2'] = {
		['name'] = 'Vigero',
		['brand'] = 'Tibus',
		['model'] = 'VIGERO2',
		['price'] = 55000,
		['category'] = 'BClass',
		['hash'] = `VIGERO2`,
		['shop'] = 'luxury',
	},
	['YOSEMITE2'] = {
		['name'] = 'YOSEMITE',
		['brand'] = 'Tibus',
		['model'] = 'YOSEMITE2',
		['price'] = 63000,
		['category'] = 'BClass',
		['hash'] = `YOSEMITE2`,
		['shop'] = 'luxury',
	},
	['FLASHGT'] = {
		['name'] = 'FLASHGT',
		['brand'] = 'Tibus',
		['model'] = 'FLASHGT',
		['price'] = 76500,
		['category'] = 'BClass',
		['hash'] = `FLASHGT`,
		['shop'] = 'luxury',
	},
	['GB200'] = {
		['name'] = 'GB200',
		['brand'] = 'Tibus',
		['model'] = 'GB200',
		['price'] = 75000,
		['category'] = 'BClass',
		['hash'] = `GB200`,
		['shop'] = 'luxury',
	},
	['CYPHER'] = {
		['name'] = 'CYPHER',
		['brand'] = 'Tibus',
		['model'] = 'CYPHER',
		['price'] = 85000,
		['category'] = 'BClass',
		['hash'] = `CYPHER`,
		['shop'] = 'luxury',
	},
	['EUROS'] = {
		['name'] = 'EUROS',
		['brand'] = 'Tibus',
		['model'] = 'EUROS',
		['price'] = 83000,
		['category'] = 'BClass',
		['hash'] = `EUROS`,
		['shop'] = 'luxury',
	},
	['GROWLER'] = {
		['name'] = 'GROWLER',
		['brand'] = 'Tibus',
		['model'] = 'GROWLER',
		['price'] = 115000,
		['category'] = 'BClass',
		['hash'] = `GROWLER`,
		['shop'] = 'luxury',
	},
	['JESTER4'] = {
		['name'] = 'JESTER',
		['brand'] = 'Tibus',
		['model'] = 'JESTER4',
		['price'] = 105000,
		['category'] = 'BClass',
		['hash'] = `JESTER4`,
		['shop'] = 'luxury',
	},
	['VECTRE'] = {
		['name'] = 'VECTRE',
		['brand'] = 'Tibus',
		['model'] = 'VECTRE',
		['price'] = 90000,
		['category'] = 'BClass',
		['hash'] = `VECTRE`,
		['shop'] = 'luxury',
	},
	['DRAFTER'] = {
		['name'] = 'DRAFTER',
		['brand'] = 'Tibus',
		['model'] = 'DRAFTER',
		['price'] = 85500,
		['category'] = 'BClass',
		['hash'] = `DRAFTER`,
		['shop'] = 'luxury',
	},
	['VSTR'] = {
		['name'] = 'VSTR',
		['brand'] = 'Tibus',
		['model'] = 'VSTR',
		['price'] = 94500,
		['category'] = 'BClass',
		['hash'] = `VSTR`,
		['shop'] = 'luxury',
	},
	['TAILGATER2'] = {
		['name'] = 'TAILGATER',
		['brand'] = 'Tibus',
		['model'] = 'TAILGATER2',
		['price'] = 75000,
		['category'] = 'BClass',
		['hash'] = `TAILGATER2`,
		['shop'] = 'luxury',
	},
	['OMNISEGT'] = {
		['name'] = 'OMNISE GT',
		['brand'] = 'Tibus',
		['model'] = 'OMNISEGT',
		['price'] = 103000,
		['category'] = 'BClass',
		['hash'] = `OMNISEGT`,
		['shop'] = 'luxury',
	},
	['RHINEHART'] = {
		['name'] = 'RHINEHART',
		['brand'] = 'Tibus',
		['model'] = 'RHINEHART',
		['price'] = 85000,
		['category'] = 'BClass',
		['hash'] = `RHINEHART`,
		['shop'] = 'luxury',
	},
	
	-- VANILLA CClass
	
	['PEYOTE3'] = {
		['name'] = 'PEYOTE',
		['brand'] = 'Tibus',
		['model'] = 'PEYOTE3',
		['price'] = 35000,
		['category'] = 'CClass',
		['hash'] = `PEYOTE3`,
		['shop'] = 'luxury',
	},

	['BISON'] = {
		['name'] = 'BISON',
		['brand'] = 'Tibus',
		['model'] = 'BISON',
		['price'] = 39000,
		['category'] = 'CClass',
		['hash'] = `BISON`,
		['shop'] = 'luxury',
	},
	['BOBCATXL'] = {
		['name'] = 'BOBCATXL',
		['brand'] = 'Tibus',
		['model'] = 'BOBCATXL',
		['price'] = 43000,
		['category'] = 'CClass',
		['hash'] = `BOBCATXL`,
		['shop'] = 'luxury',
	},
	['SADLER'] = {
		['name'] = 'SADLER',
		['brand'] = 'Tibus',
		['model'] = 'SADLER',
		['price'] = 46500,
		['category'] = 'CClass',
		['hash'] = `SADLER`,
		['shop'] = 'luxury',
	},
	['SANDKING'] = {
		['name'] = 'SANDKING',
		['brand'] = 'Tibus',
		['model'] = 'SANDKING',
		['price'] = 75000,
		['category'] = 'CClass',
		['hash'] = `SANDKING`,
		['shop'] = 'luxury',
	},
	
	['GUARDIAN'] = {
		['name'] = 'GUARDIAN',
		['brand'] = 'Tibus',
		['model'] = 'GUARDIAN',
		['price'] = 79000,
		['category'] = 'CClass',
		['hash'] = `GUARDIAN`,
		['shop'] = 'luxury',
	},
	['EVERON'] = {
		['name'] = 'EVERON',
		['brand'] = 'Tibus',
		['model'] = 'EVERON',
		['price'] = 92000,
		['category'] = 'CClass',
		['hash'] = `EVERON`,
		['shop'] = 'luxury',
	},
	['CARACARA2'] = {
		['name'] = 'CARACARA',
		['brand'] = 'Tibus',
		['model'] = 'CARACARA2',
		['price'] = 85000,
		['category'] = 'CClass',
		['hash'] = `CARACARA2`,
		['shop'] = 'luxury',
	},
	['DRAUGUR'] = {
		['name'] = 'DRAUGUR',
		['brand'] = 'Tibus',
		['model'] = 'DRAUGUR',
		['price'] = 80000,
		['category'] = 'CClass',
		['hash'] = `DRAUGUR`,
		['shop'] = 'luxury',
	},
	['NOVAK'] = {
		['name'] = 'NOVAK',
		['brand'] = 'Tibus',
		['model'] = 'NOVAK',
		['price'] = 47500,
		['category'] = 'CClass',
		['hash'] = `NOVAK`,
		['shop'] = 'luxury',
	},
	['JUBILEE'] = {
		['name'] = 'JUBILEE',
		['brand'] = 'Tibus',
		['model'] = 'JUBILEE',
		['price'] = 93750,
		['category'] = 'CClass',
		['hash'] = `JUBILEE`,
		['shop'] = 'luxury',
	},
	['ASTRON'] = {
		['name'] = 'ASTRON',
		['brand'] = 'Tibus',
		['model'] = 'ASTRON',
		['price'] = 73000,
		['category'] = 'CClass',
		['hash'] = `ASTRON`,
		['shop'] = 'luxury',
	},
	['BALLER3'] = {
		['name'] = 'BALLER',
		['brand'] = 'Tibus',
		['model'] = 'BALLER3',
		['price'] = 65000,
		['category'] = 'CClass',
		['hash'] = `BALLER3`,
		['shop'] = 'luxury',
	},
	['JESTER3'] = {
		['name'] = 'JESTER SR',
		['brand'] = 'Tibus',
		['model'] = 'JESTER3',
		['price'] = 55500,
		['category'] = 'CClass',
		['hash'] = `JESTER3`,
		['shop'] = 'luxury',
	},
	['KANJO'] = {
		['name'] = 'KANJO',
		['brand'] = 'Tibus',
		['model'] = 'KANJO',
		['price'] = 37000,
		['category'] = 'CClass',
		['hash'] = `KANJO`,
		['shop'] = 'luxury',
	},
	['PENUMBRA2'] = {
		['name'] = 'PENUMBRA',
		['brand'] = 'Tibus',
		['model'] = 'PENUMBRA2',
		['price'] = 42300,
		['category'] = 'CClass',
		['hash'] = `PENUMBRA2`,
		['shop'] = 'luxury',
	},
	['CALICO'] = {
		['name'] = 'CALICO',
		['brand'] = 'Tibus',
		['model'] = 'CALICO',
		['price'] = 39000,
		['category'] = 'CClass',
		['hash'] = `CALICO`,
		['shop'] = 'luxury',
	},
	['REMUS'] = {
		['name'] = 'REMUS',
		['brand'] = 'Tibus',
		['model'] = 'REMUS',
		['price'] = 36100,
		['category'] = 'CClass',
		['hash'] = `REMUS`,
		['shop'] = 'luxury',
	},
	['RT3000'] = {
		['name'] = 'RT3000',
		['brand'] = 'Tibus',
		['model'] = 'RT3000',
		['price'] = 33500,
		['category'] = 'CClass',
		['hash'] = `RT3000`,
		['shop'] = 'luxury',
	},
	['SULTAN2'] = {
		['name'] = 'SULTAN',
		['brand'] = 'Tibus',
		['model'] = 'SULTAN2',
		['price'] = 43500,
		['category'] = 'CClass',
		['hash'] = `SULTAN2`,
		['shop'] = 'luxury',
	},
	['KURUMA'] = {
		['name'] = 'KURUMA',
		['brand'] = 'Tibus',
		['model'] = 'KURUMA',
		['price'] = 49000,
		['category'] = 'CClass',
		['hash'] = `KURUMA`,
		['shop'] = 'luxury',
	},
	['SUGOI'] = {
		['name'] = 'SUGOI',
		['brand'] = 'Tibus',
		['model'] = 'SUGOI',
		['price'] = 38000,
		['category'] = 'CClass',
		['hash'] = `SUGOI`,
		['shop'] = 'luxury',
	},
	
	
	
	-- VANILLA DClass
	
	['RUMPO'] = {
		['name'] = 'RUMPO',
		['brand'] = 'Tibus',
		['model'] = 'RUMPO',
		['price'] = 23000,
		['category'] = 'DClass',
		['hash'] = `RUMPO`,
		['shop'] = 'luxury',
	},
	['speedo'] = {
		['name'] = 'speedo',
		['brand'] = 'Tibus',
		['model'] = 'speedo',
		['price'] = 25000,
		['category'] = 'DClass',
		['hash'] = `speedo`,
		['shop'] = 'luxury',
	},
	['SURFER'] = {
		['name'] = 'SURFER',
		['brand'] = 'Tibus',
		['model'] = 'SURFER',
		['price'] = 24000,
		['category'] = 'DClass',
		['hash'] = `SURFER`,
		['shop'] = 'luxury',
	},
	['YOUGA2'] = {
		['name'] = 'YOUGA',
		['brand'] = 'Tibus',
		['model'] = 'YOUGA2',
		['price'] = 21000,
		['category'] = 'DClass',
		['hash'] = `YOUGA2`,
		['shop'] = 'luxury',
	},
	['YOUGA3'] = {
		['name'] = 'YOUGA 4x4',
		['brand'] = 'Tibus',
		['model'] = 'YOUGA3',
		['price'] = 21000,
		['category'] = 'DClass',
		['hash'] = `YOUGA3`,
		['shop'] = 'luxury',
	},
	['MOONBEAM'] = {
		['name'] = 'MOONBEAM',
		['brand'] = 'Tibus',
		['model'] = 'MOONBEAM',
		['price'] = 28000,
		['category'] = 'DClass',
		['hash'] = `MOONBEAM`,
		['shop'] = 'luxury',
	},

	['PRIMO2'] = {
		['name'] = 'PRIMO',
		['brand'] = 'Tibus',
		['model'] = 'PRIMO2',
		['price'] = 18000,
		['category'] = 'DClass',
		['hash'] = `PRIMO2`,
		['shop'] = 'luxury',
	},
	['FACTION3'] = {
		['name'] = 'FACTION',
		['brand'] = 'Tibus',
		['model'] = 'FACTION3',
		['price'] = 23000,
		['category'] = 'DClass',
		['hash'] = `FACTION3`,
		['shop'] = 'luxury',
	},
	['MINIVAN2'] = {
		['name'] = 'MINIVAN',
		['brand'] = 'Tibus',
		['model'] = 'MINIVAN2',
		['price'] = 20000,
		['category'] = 'DClass',
		['hash'] = `MINIVAN2`,
		['shop'] = 'luxury',
	},
	['SABREGT2'] = {
		['name'] = 'SABRE GT',
		['brand'] = 'Tibus',
		['model'] = 'SABREGT2',
		['price'] = 15000,
		['category'] = 'DClass',
		['hash'] = `SABREGT2`,
		['shop'] = 'luxury',
	},
	['TORNADO5'] = {
		['name'] = 'TORNADO',
		['brand'] = 'Tibus',
		['model'] = 'TORNADO5',
		['price'] = 12750,
		['category'] = 'DClass',
		['hash'] = `TORNADO5`,
		['shop'] = 'luxury',
	},
	['VIRGO2'] = {
		['name'] = 'VIRGO',
		['brand'] = 'Tibus',
		['model'] = 'VIRGO2',
		['price'] = 17500,
		['category'] = 'DClass',
		['hash'] = `VIRGO2`,
		['shop'] = 'luxury',
	},
	['GLENDALE2'] = {
		['name'] = 'GLENDALE',
		['brand'] = 'Tibus',
		['model'] = 'GLENDALE2',
		['price'] = 9000,
		['category'] = 'DClass',
		['hash'] = `GLENDALE2`,
		['shop'] = 'luxury',
	},
	['MANANA2'] = {
		['name'] = 'MANANA',
		['brand'] = 'Tibus',
		['model'] = 'MANANA2',
		['price'] = 22500,
		['category'] = 'DClass',
		['hash'] = `MANANA2`,
		['shop'] = 'luxury',
	},
	['DYNASTY'] = {
		['name'] = 'DYNASTY',
		['brand'] = 'Tibus',
		['model'] = 'DYNASTY',
		['price'] = 15000,
		['category'] = 'DClass',
		['hash'] = `DYNASTY`,
		['shop'] = 'luxury',
	},

	-- NITRO VEHICLES
	['RAPTOR'] = {
		['name'] = 'RAPTOR',
		['brand'] = 'Tibus',
		['model'] = 'RAPTOR',
		['price'] = 65000,
		['category'] = 'Nitro',
		['hash'] = `RAPTOR`,
		['shop'] = 'NITRO',
	},
	['VAGRANT'] = {
		['name'] = 'VAGRANT',
		['brand'] = 'Tibus',
		['model'] = 'VAGRANT',
		['price'] = 45000,
		['category'] = 'Nitro',
		['hash'] = `VAGRANT`,
		['shop'] = 'NITRO',
	},
	['VETO'] = {
		['name'] = 'VETO',
		['brand'] = 'Tibus',
		['model'] = 'VETO',
		['price'] = 25000,
		['category'] = 'Nitro',
		['hash'] = `VETO`,
		['shop'] = 'NITRO',
	},
	['OUTLAW'] = {
		['name'] = 'OUTLAW',
		['brand'] = 'Tibus',
		['model'] = 'OUTLAW',
		['price'] = 50000,
		['category'] = 'Nitro',
		['hash'] = `OUTLAW`,
		['shop'] = 'NITRO',
	},
	['VERUS'] = {
		['name'] = 'VERUS',
		['brand'] = 'Tibus',
		['model'] = 'VERUS',
		['price'] = 33000,
		['category'] = 'Nitro',
		['hash'] = `VERUS`,
		['shop'] = 'NITRO',
	},
	['STRYDER'] = {
		['name'] = 'STRYDER',
		['brand'] = 'Tibus',
		['model'] = 'STRYDER',
		['price'] = 25000,
		['category'] = 'Nitro',
		['hash'] = `STRYDER`,
		['shop'] = 'NITRO',
	},
	-- MOTO
	['FLHXS_STREETGLIDE_SPECIAL18'] = {
		['name'] = 'Streetglide',
		['brand'] = 'Tibus',
		['model'] = 'FLHXS_STREETGLIDE_SPECIAL18',
		['price'] = 115000,
		['category'] = 'Moto',
		['hash'] = `FLHXS_STREETGLIDE_SPECIAL18`,
		['shop'] = 'luxury',
	},
	['HDIron883'] = {
		['name'] = 'Iron883',
		['brand'] = 'Harley Davidson',
		['model'] = 'HDIron883',
		['price'] = 120000,
		['category'] = 'Moto',
		['hash'] = `HDIron883`,
		['shop'] = 'luxury',
	},
	['naglfar'] = {
		['name'] = 'Naglfar',
		['brand'] = 'Tibus',
		['model'] = 'naglfar',
		['price'] = 82500,
		['category'] = 'Moto',
		['hash'] = `naglfar`,
		['shop'] = 'luxury',
	},
	['DAEMON2'] = {
		['name'] = 'DAEMON',
		['brand'] = 'Tibus',
		['model'] = 'DAEMON2',
		['price'] = 55000,
		['category'] = 'Moto',
		['hash'] = `DAEMON2`,
		['shop'] = 'luxury',
	},
	['HEXER'] = {
		['name'] = 'HEXER',
		['brand'] = 'Tibus',
		['model'] = 'HEXER',
		['price'] = 55000,
		['category'] = 'Moto',
		['hash'] = `HEXER`,
		['shop'] = 'luxury',
	},
	['PCJ'] = {
		['name'] = 'PCJ',
		['brand'] = 'Tibus',
		['model'] = 'PCJ',
		['price'] = 70000,
		['category'] = 'Moto',
		['hash'] = `PCJ`,
		['shop'] = 'luxury',
	},
	['sanchez'] = {
		['name'] = 'sanchez',
		['brand'] = 'Tibus',
		['model'] = 'sanchez',
		['price'] = 35000,
		['category'] = 'Moto',
		['hash'] = `sanchez`,
		['shop'] = 'luxury',
	},
	['CHIMERA'] = {
		['name'] = 'CHIMERA',
		['brand'] = 'Tibus',
		['model'] = 'CHIMERA',
		['price'] = 60000,
		['category'] = 'Moto',
		['hash'] = `CHIMERA`,
		['shop'] = 'luxury',
	},
	['DEFILER'] = {
		['name'] = 'DEFILER',
		['brand'] = 'Tibus',
		['model'] = 'DEFILER',
		['price'] = 65000,
		['category'] = 'Moto',
		['hash'] = `DEFILER`,
		['shop'] = 'luxury',
	},
	['NIGHTBLADE'] = {
		['name'] = 'NIGHTBLADE',
		['brand'] = 'Tibus',
		['model'] = 'NIGHTBLADE',
		['price'] = 55000,
		['category'] = 'Moto',
		['hash'] = `NIGHTBLADE`,
		['shop'] = 'luxury',
	},
	['ZOMBIEA'] = {
		['name'] = 'ZOMBIEA',
		['brand'] = 'Tibus',
		['model'] = 'ZOMBIEA',
		['price'] = 60000,
		['category'] = 'Moto',
		['hash'] = `ZOMBIEA`,
		['shop'] = 'luxury',
	},
	['AVARUS'] = {
		['name'] = 'AVARUS',
		['brand'] = 'Tibus',
		['model'] = 'AVARUS',
		['price'] = 55000,
		['category'] = 'Moto',
		['hash'] = `AVARUS`,
		['shop'] = 'luxury',
	},
	['SANCTUS'] = {
		['name'] = 'SANCTUS',
		['brand'] = 'Tibus',
		['model'] = 'SANCTUS',
		['price'] = 50000,
		['category'] = 'Moto',
		['hash'] = `SANCTUS`,
		['shop'] = 'luxury',
	},
	['MANCHEZ'] = {
		['name'] = 'MANCHEZ',
		['brand'] = 'Tibus',
		['model'] = 'MANCHEZ',
		['price'] = 60000,
		['category'] = 'Moto',
		['hash'] = `MANCHEZ`,
		['shop'] = 'luxury',
	},
	['FAGGIO3'] = {
		['name'] = 'FAGGIO',
		['brand'] = 'Tibus',
		['model'] = 'FAGGIO3',
		['price'] = 10000,
		['category'] = 'Moto',
		['hash'] = `FAGGIO3`,
		['shop'] = 'luxury',
	},
	['BLAZER4'] = {
		['name'] = 'BLAZER',
		['brand'] = 'Tibus',
		['model'] = 'BLAZER4',
		['price'] = 35000,
		['category'] = 'Moto',
		['hash'] = `BLAZER4`,
		['shop'] = 'luxury',
	},
	['ENDURO'] = {
		['name'] = 'ENDURO',
		['brand'] = 'Tibus',
		['model'] = 'ENDURO',
		['price'] = 60000,
		['category'] = 'Moto',
		['hash'] = `ENDURO`,
		['shop'] = 'luxury',
	},
	
	
	-- Moto +
	['bmws'] = {
		['name'] = 'S100RR',
		['brand'] = 'BMW',
		['model'] = 'bmws',
		['price'] = 250000,
		['category'] = 'Moto',
		['hash'] = `bmws`,
		['shop'] = 'luxury',
	},
	['cbr1000rrr'] = {
		['name'] = 'CBR100R',
		['brand'] = 'Honda',
		['model'] = 'cbr1000rrr',
		['price'] = 250000,
		['category'] = 'Supporter',
		['hash'] = `cbr1000rrr`,
		['shop'] = 'Supporter',
	},
	['r1'] = {
		['name'] = 'R1',
		['brand'] = 'Yamaha',
		['model'] = 'r1',
		['price'] = 230000,
		['category'] = 'Moto',
		['hash'] = `r1`,
		['shop'] = 'luxury',
	},

	['DOUBLE'] = {
		['name'] = 'DOUBLE T',
		['brand'] = 'Tibus',
		['model'] = 'DOUBLE',
		['price'] = 180000,
		['category'] = 'Moto',
		['hash'] = `DOUBLE`,
		['shop'] = 'luxury',
	},
	['BATI'] = {
		['name'] = 'BATI',
		['brand'] = 'Tibus',
		['model'] = 'BATI',
		['price'] = 160000,
		['category'] = 'Moto',
		['hash'] = `BATI`,
		['shop'] = 'luxury',
	},
	['RUFFIAN'] = {
		['name'] = 'RUFFIAN',
		['brand'] = 'Tibus',
		['model'] = 'RUFFIAN',
		['price'] = 155000,
		['category'] = 'Moto',
		['hash'] = `RUFFIAN`,
		['shop'] = 'luxury',
	},
	['VORTEX'] = {
		['name'] = 'VORTEX',
		['brand'] = 'Tibus',
		['model'] = 'VORTEX',
		['price'] = 175000,
		['category'] = 'Moto',
		['hash'] = `VORTEX`,
		['shop'] = 'luxury',
	},
	['HAKUCHOU2'] = {
		['name'] = 'HAKUCHOU',
		['brand'] = 'Tibus',
		['model'] = 'HAKUCHOU2',
		['price'] = 195000,
		['category'] = 'Moto',
		['hash'] = `HAKUCHOU2`,
		['shop'] = 'luxury',
	},
	['DIABLOUS2'] = {
		['name'] = 'DIABLOUS',
		['brand'] = 'Tibus',
		['model'] = 'DIABLOUS2',
		['price'] = 140000,
		['category'] = 'Moto',
		['hash'] = `DIABLOUS2`,
		['shop'] = 'luxury',
	},
	['FCR2'] = {
		['name'] = 'FCR2',
		['brand'] = 'Tibus',
		['model'] = 'FCR2',
		['price'] = 130000,
		['category'] = 'Moto',
		['hash'] = `FCR2`,
		['shop'] = 'luxury',
	},
	 -- DIAMOND VEHICLES
	 
	 ['e63amg'] = {							
		['name'] = 'E63',
		['brand'] = 'Kevin',
		['model'] = 'e63amg',
		['price'] = 480000,
		['category'] = 'AClass',
		['hash'] = `e63amg`,
		['shop'] = '',
     },
	 
	 ['GMCAND'] = {							
		['name'] = 'GMC',
		['brand'] = 'N00B5TR',
		['model'] = 'GMCAND',
		['price'] = 350000,
		['category'] = 'BClass',
		['hash'] = `GMCAND`,
		['shop'] = '',
     },
	 ['m2ac'] = {							
		['name'] = 'M2',
		['brand'] = 'Thomas',
		['model'] = 'm2ac',
		['price'] = 390000,
		['category'] = 'AClass',
		['hash'] = `m2ac`,
		['shop'] = '',
     },
	 ['DUERTA'] = {							
		['name'] = 'DUERTA',
		['brand'] = 'Rufio',
		['model'] = 'DUERTA',
		['price'] = 1100000,
		['category'] = 'SClass',
		['hash'] = `DUERTA`,
		['shop'] = '',
     },
	 ['ugcthawk'] = {							
		['name'] = 'Hellhawk',
		['brand'] = 'Panny',
		['model'] = 'ugcthawk',
		['price'] = 700000,
		['category'] = 'SClass',
		['hash'] = `ugcthawk`,
		['shop'] = '',
     },
	 ['carsonspriorurus'] = {							
		['name'] = 'Urus Prior Design',
		['brand'] = 'Lamborghini',
		['model'] = 'carsonspriorurus',
		['price'] = 680000,
		['category'] = 'Supporter',
		['hash'] = `carsonspriorurus`,
		['shop'] = 'Supporter',
     },
	 ['g63byv'] = {							
		['name'] = '6 Seater G63',
		['brand'] = 'Mercedes',
		['model'] = 'g63byv',
		['price'] = 5000,
		['category'] = 'BClass',
		['hash'] = `g63byv`,
		['shop'] = '',
     },
	 ['rmodm4gts'] = {							
		['name'] = 'M4 GTS',
		['brand'] = 'Loki',
		['model'] = 'rmodm4gts',
		['price'] = 450000,
		['category'] = 'AClass',
		['hash'] = `rmodm4gts`,
		['shop'] = '',
     },
	 ['rmodrs7'] = {							
		['name'] = 'RS7',
		['brand'] = 'Lupo',
		['model'] = 'rmodrs7',
		['price'] = 410000,
		['category'] = 'AClass',
		['hash'] = `rmodrs7`,
		['shop'] = '',
     },
	 ['rs6abt20'] = {							
		['name'] = 'RS6',
		['brand'] = 'Florence',
		['model'] = 'rs6abt20',
		['price'] = 380000,
		['category'] = 'AClass',
		['hash'] = `rs6abt20`,
		['shop'] = '',
     },
	 ['KAMACHO'] = {
		['name'] = 'KAMACHO',
		['brand'] = 'Mooe',
		['model'] = 'KAMACHO',
		['price'] = 150000,
		['category'] = 'CClass',
		['hash'] = `KAMACHO`,
		['shop'] = '',
	},
	['chargerdemon'] = {
		['name'] = 'Charger Demon',
		['brand'] = 'Ocyris',
		['model'] = 'chargerdemon',
		['price'] = 650000,
		['category'] = 'AClass',
		['hash'] = `chargerdemon`,
		['shop'] = '',
	},
	
	 ['amels200'] = {
		['name'] = 'Amels 200',
		['brand'] = 'CECE',
		['model'] = 'amels200',
		['price'] = 3000000,
		['category'] = 'boats',
		['hash'] = `amels200`,
		['shop'] = '',
	},
		-- Boats
	['squalo'] = {
		['name'] = 'Squalo',
		['brand'] = 'Shitzu',
		['model'] = 'squalo',
		['price'] = 25000,
		['category'] = 'boats',
		['hash'] = `squalo`,
		['shop'] = 'boats',
	},
	['marquis'] = {
		['name'] = 'Marquis',
		['brand'] = 'Dinka',
		['model'] = 'marquis',
		['price'] = 100000,
		['category'] = 'boats',
		['hash'] = `marquis`,
		['shop'] = 'boats',
	},
	['AVISA'] = {
		['name'] = 'AVISA',
		['brand'] = 'Tibus',
		['model'] = 'AVISA',
		['price'] = 1500000,
		['category'] = 'boats',
		['hash'] = `AVISA`,
		['shop'] = 'boats',
	},
	['jetmax'] = {
		['name'] = 'Shitzu',
		['brand'] = 'Jetmax',
		['model'] = 'jetmax',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `jetmax`,
		['shop'] = 'boats',
	},
	['tropic'] = {
		['name'] = 'Shitzu',
		['brand'] = 'Tropic',
		['model'] = 'tropic',
		['price'] = 20000,
		['category'] = 'boats',
		['hash'] = `tropic`,
		['shop'] = 'boats',
	},
	['speeder'] = {
		['name'] = 'Speeder',
		['brand'] = 'Pegassi',
		['model'] = 'speeder',
		['price'] = 92500,
		['category'] = 'boats',
		['hash'] = `speeder`,
		['shop'] = 'boats',
	},
	['longfin'] = {
		['name'] = 'Longfin',
		['brand'] = 'Shitzu',
		['model'] = 'longfin',
		['price'] = 155000,
		['category'] = 'boats',
		['hash'] = `longfin`,
		['shop'] = 'boats',
	},
	['toro2'] = {
		['name'] = 'Toro',
		['brand'] = 'Lampadati',
		['model'] = 'toro2',
		['price'] = 189500,
		['category'] = 'boats',
		['hash'] = `toro2`,
		['shop'] = 'boats',
	},
	['seashark'] = {
		['name'] = 'seashark',
		['brand'] = 'Tibus',
		['model'] = 'seashark',
		['price'] = 50000,
		['category'] = 'boats',
		['hash'] = `seashark`,
		['shop'] = 'boats',
	},
	
	['sr650fly'] = {
		['name'] = 'Sr650fly',
		['brand'] = 'Tibus',
		['model'] = 'sr650fly',
		['price'] = 1420000,
		['category'] = 'boats',
		['hash'] = `sr650fly`,
		['shop'] = 'boats',
	},
	['yaluxe'] = {
		['name'] = 'Yaluxe',
		['brand'] = 'Tibus',
		['model'] = 'yaluxe',
		['price'] = 5000000,
		['category'] = 'boats',
		['hash'] = `yaluxe`,
		['shop'] = 'boats',
	},
	-- helicopters
	
	['frogger'] = {
		['name'] = 'Frogger',
		['brand'] = 'Unknown',
		['model'] = 'frogger',
		['price'] = 375000,
		['category'] = 'helicopters',
		['hash'] = `frogger`,
		['shop'] = 'air',
	},
	['swift'] = {
		['name'] = 'Swift',
		['brand'] = 'Buckingham',
		['model'] = 'swift',
		['price'] = 750000,
		['category'] = 'helicopters',
		['hash'] = `swift`,
		['shop'] = 'air',
	},
	['swift2'] = {
		['name'] = 'Golden Swift',
		['brand'] = 'Buckingham',
		['model'] = 'swift2',
		['price'] = 1300000,
		['category'] = 'helicopters',
		['hash'] = `swift2`,
		['shop'] = 'air',
	},
	['seasparrow'] = {
		['name'] = 'Sea Sparrow',
		['brand'] = 'Unknown',
		['model'] = 'seasparrow',
		['price'] = 450000,
		['category'] = 'helicopters',
		['hash'] = `seasparrow`,
		['shop'] = 'air',
	},
	['supervolito2'] = {
		['name'] = 'SuperVolito Carbon',
		['brand'] = 'Buckingham',
		['model'] = 'supervolito2',
		['price'] = 1050000,
		['category'] = 'helicopters',
		['hash'] = `supervolito2`,
		['shop'] = 'air',
	},
	['volatus'] = {
		['name'] = 'Volatus',
		['brand'] = 'Buckingham',
		['model'] = 'volatus',
		['price'] = 775000,
		['category'] = 'helicopters',
		['hash'] = `volatus`,
		['shop'] = 'air',
	},
	['havok'] = {
		['name'] = 'Havok',
		['brand'] = 'Nagasaki',
		['model'] = 'havok',
		['price'] = 250000,
		['category'] = 'helicopters',
		['hash'] = `havok`,
		['shop'] = 'air',
	},
	['CONADA'] = {
		['name'] = 'CONADA',
		['brand'] = 'Tibus',
		['model'] = 'CONADA',
		['price'] = 450000,
		['category'] = 'helicopters',
		['hash'] = `CONADA`,
		['shop'] = 'air',
	},
	-- Planes
	['mammatus'] = {
		['name'] = 'Mammatus',
		['brand'] = 'Tibus',
		['model'] = 'mammatus',
		['price'] = 480000,
		['category'] = 'planes',
		['hash'] = `mammatus`,
		['shop'] = 'air',
	},
	['velum'] = {
		['name'] = 'Velum',
		['brand'] = 'Tibus',
		['model'] = 'velum',
		['price'] = 475000,
		['category'] = 'planes',
		['hash'] = `velum`,
		['shop'] = 'air',
	},
	['vestra'] = {
		['name'] = 'Vestra',
		['brand'] = 'Buckingham',
		['model'] = 'vestra',
		['price'] = 600000,
		['category'] = 'planes',
		['hash'] = `vestra`,
		['shop'] = 'air',
	},
	['dodo'] = {
		['name'] = 'Dodo',
		['brand'] = 'Mammoth',
		['model'] = 'dodo',
		['price'] = 550000,
		['category'] = 'planes',
		['hash'] = `dodo`,
		['shop'] = 'air',
	},
	['alphaz1'] = {
		['name'] = 'Alpha-Z1',
		['brand'] = 'Tibus',
		['model'] = 'alphaz1',
		['price'] = 625000,
		['category'] = 'planes',
		['hash'] = `alphaz1`,
		['shop'] = 'air',
	},
	['nimbus'] = {
		['name'] = 'Nimbus',
		['brand'] = 'Tibus',
		['model'] = 'nimbus',
		['price'] = 1100000,
		['category'] = 'planes',
		['hash'] = `nimbus`,
		['shop'] = 'air',
	},		

	['CUBAN800'] = {
		['name'] = 'CUBAN800',
		['brand'] = 'Tibus',
		['model'] = 'CUBAN800',
		['price'] = 425000,
		['category'] = 'planes',
		['hash'] = `CUBAN800`,
		['shop'] = 'air',
	},
	['luxor2'] = {
		['name'] = 'luxor',
		['brand'] = 'Tibus',
		['model'] = 'luxor2',
		['price'] = 1500000,
		['category'] = 'planes',
		['hash'] = `luxor2`,
		['shop'] = 'air',
	},	
	['SEABREEZE'] = {
		['name'] = 'SEABREEZE',
		['brand'] = 'Tibus',
		['model'] = 'SEABREEZE',
		['price'] = 900000,
		['category'] = 'planes',
		['hash'] = `SEABREEZE`,
		['shop'] = 'air',
	},
	['MICROLIGHT'] = {
		['name'] = 'MICROLIGHT',
		['brand'] = 'Tibus',
		['model'] = 'MICROLIGHT',
		['price'] = 190000,
		['category'] = 'planes',
		['hash'] = `MICROLIGHT`,
		['shop'] = 'air',
	},	
	 -- LSPD
	 ['polas350'] = {							
		['name'] = 'AIRONE',
		['brand'] = 'LSPD',
		['model'] = 'polas350',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `polas350`,
		['shop'] = '',
     },
	 ['n18charger'] = {							
		['name'] = 'LSPD Charger',
		['brand'] = 'LSPD',
		['model'] = 'n18charger',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `n18charger`,
		['shop'] = '',
     },
	 ['n12caprice'] = {							
		['name'] = 'LSPD Caprice',
		['brand'] = 'LSPD',
		['model'] = 'n12caprice',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `n12caprice`,
		['shop'] = '',
     },
	 ['n19tahoe'] = {							
		['name'] = 'LSPD Tahoe',
		['brand'] = 'LSPD',
		['model'] = 'n19tahoe',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `n19tahoe`,
		['shop'] = '',
     },
	 ['n18taurus'] = {							
		['name'] = 'LSPD Taurus',
		['brand'] = 'LSPD',
		['model'] = 'n18taurus',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `n18taurus`,
		['shop'] = '',
     },
	 ['n16explorer'] = {							
		['name'] = 'LSPD Explorer',
		['brand'] = 'LSPD',
		['model'] = 'n16explorer',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `n16explorer`,
		['shop'] = '',
     },
	 ['n18f150'] = {							
		['name'] = 'LSPD F150',
		['brand'] = 'LSPD',
		['model'] = 'n18f150',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `n18f150`,
		['shop'] = '',
     },
	 ['n16impala'] = {							
		['name'] = 'LSPD Impala',
		['brand'] = 'LSPD',
		['model'] = 'n16impala',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `n16impala`,
		['shop'] = '',
     },
	 ['n19mustang'] = {							
		['name'] = 'LSPD Mustang',
		['brand'] = 'LSPD',
		['model'] = 'n19mustang',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `n19mustang`,
		['shop'] = '',
     },
	 ['n11vic'] = {							
		['name'] = 'LSPD CrownVic',
		['brand'] = 'LSPD',
		['model'] = 'n11vic',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `n11vic`,
		['shop'] = '',
     },
	 ['21ramtrx'] = {							
		['name'] = 'TRX',
		['brand'] = 'LSPD',
		['model'] = '21ramtrx',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `21ramtrx`,
		['shop'] = '',
     },
	
	 -- Misc
	 ['bcat'] = {							
		['name'] = 'Bearcat',
		['brand'] = 'FED',
		['model'] = 'bcat',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `bcat`,
		['shop'] = '',
     },
	 ['mrap'] = {							
		['name'] = 'Bearcat',
		['brand'] = 'FED',
		['model'] = 'mrap',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `mrap`,
		['shop'] = '',
     },
	 ['909_v21tahoe'] = {							
		['name'] = 'Tahoe',
		['brand'] = 'FED',
		['model'] = '909_v21tahoe',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `909_v21tahoe`,
		['shop'] = '',
     },
	 ['david_escalade'] = {							
		['name'] = 'Escalade',
		['brand'] = 'FED',
		['model'] = 'david_escalade',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `david_escalade`,
		['shop'] = '',
     },
	 ['donator_19sierra'] = {							
		['name'] = 'Sierra',
		['brand'] = 'FED',
		['model'] = 'donator_19sierra',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `donator_19sierra`,
		['shop'] = '',
     },
	 ['pack6tundra'] = {							
		['name'] = 'Tundra',
		['brand'] = 'FED',
		['model'] = 'pack6tundra',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `pack6tundra`,
		['shop'] = '',
     },
	 ['polmav'] = {							
		['name'] = 'Air-One',
		['brand'] = 'FED',
		['model'] = 'polmav',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `polmav`,
		['shop'] = '',
     },
	 -- SAFD
	 ['brush'] = {							
		['name'] = 'Brush',
		['brand'] = 'SAFD',
		['model'] = 'brush',
		['price'] = 5000,
		['category'] = 'safd',
		['hash'] = `brush`,
		['shop'] = '',
     },
	 ['emsaw139'] = {							
		['name'] = 'EMS HELI',
		['brand'] = 'SAFD',
		['model'] = 'emsaw139',
		['price'] = 5000,
		['category'] = 'safd',
		['hash'] = `emsaw139`,
		['shop'] = '',
     },
	 ['enforcerf'] = {							
		['name'] = 'Engine 9',
		['brand'] = 'SAFD',
		['model'] = 'enforcerf',
		['price'] = 5000,
		['category'] = 'safd',
		['hash'] = `enforcerf`,
		['shop'] = '',
     },
	 ['LARGEBOAT'] = {							
		['name'] = 'Rescue Boat',
		['brand'] = 'SAFD',
		['model'] = 'LARGEBOAT',
		['price'] = 5000,
		['category'] = 'safd',
		['hash'] = `LARGEBOAT`,
		['shop'] = '',
     },
	 ['fpispov'] = {							
		['name'] = 'Taurus',
		['brand'] = 'SAFD',
		['model'] = 'fpispov',
		['price'] = 5000,
		['category'] = 'safd',
		['hash'] = `fpispov`,
		['shop'] = '',
     },
	 
	 ['safr412'] = {							
		['name'] = '412',
		['brand'] = 'SAFD',
		['model'] = 'safr412',
		['price'] = 5000,
		['category'] = 'safd',
		['hash'] = `safr412`,
		['shop'] = '',
     },
	 ['fordambo'] = {							
		['name'] = 'SAFD Ambulance',
		['brand'] = 'SAFD',
		['model'] = 'fordambo',
		['price'] = 5000,
		['category'] = 'safd',
		['hash'] = `fordambo`,
		['shop'] = '',
     },
	
	 ['fpiupov'] = {							
		['name'] = 'SAFD Explorer',
		['brand'] = 'SAFD',
		['model'] = 'fpiupov',
		['price'] = 5000,
		['category'] = 'safd',
		['hash'] = `fpiupov`,
		['shop'] = '',
     },
	
	

	 -- EVENT VEHICLES
	 ['xmassubi'] = {							
		['name'] = 'SUBUWU',
		['brand'] = 'XMAS',
		['model'] = 'xmassubi',
		['price'] = 5000,
		['category'] = 'event',
		['hash'] = `xmassubi`,
		['shop'] = '',
     },

	 -- Unused Local Vehicles
	['gauntlet5'] = {							
		['name'] = 'Gauntlet Classic Custom',
		['brand'] = 'Tibus',
		['model'] = 'gauntlet5',
		['price'] = 5000,
		['category'] = 'AClass',
		['hash'] = `gauntlet5`,
		['shop'] = '',
     },

	 ['yosemite3'] = {							
		['name'] = 'Gauntlet Classic Custom',
		['brand'] = 'Tibus',
		['model'] = 'yosemite3',
		['price'] = 5000,
		['category'] = 'BClass',
		['hash'] = `yosemite3`,
		['shop'] = '',
     },

     ['dukes3'] = {							
		['name'] = 'Beater Dukes',
		['brand'] = 'Tibus',
		['model'] = 'dukes3',
		['price'] = 5000,
		['category'] = 'AClass',
		['hash'] = `dukes3`,
		['shop'] = '',
     },

     ['seminole2'] = {							
		['name'] = 'Seminole Frontier',
		['brand'] = 'Tibus',
		['model'] = 'seminole2',
		['price'] = 5000,
		['category'] = '',
		['hash'] = `seminole2`,
		['shop'] = '',
     },

     ['landstalker2'] = {							
		['name'] = 'Landstalker XL',
		['brand'] = 'Tibus',
		['model'] = 'landstalker2',
		['price'] = 5000,
		['category'] = 'BClass',
		['hash'] = `landstalker2`,
		['shop'] = '',
     },
     ['club'] = {							
		['name'] = 'Club',
		['brand'] = 'Tibus',
		['model'] = 'club',
		['price'] = 5000,
		['category'] = 'DClass',
		['hash'] = `club`,
		['shop'] = '',
     },
     ['tigon'] = {							
		['name'] = 'Tigon',
		['brand'] = 'Tibus',
		['model'] = 'tigon',
		['price'] = 5000,
		['category'] = 'SClass',
		['hash'] = `tigon`,
		['shop'] = '',
     },
     ['openwheel2'] = {							
		['name'] = 'DR1(indycar)',
		['brand'] = 'Tibus',
		['model'] = 'openwheel2',
		['price'] = 5000,
		['category'] = 'ZClass',
		['hash'] = `openwhee2`,
		['shop'] = '',
     },
     ['openwheel1'] = {							
		['name'] = 'BR8(Formula 1 Car)',
		['brand'] = 'Tibus',
		['model'] = 'openwheel1',
		['price'] = 5000,
		['category'] = 'ZClass',
		['hash'] = `openwheel1`,
		['shop'] = '',
     },
     ['rebla'] = {							
		['name'] = 'Rebla GTS',
		['brand'] = 'Tibus',
		['model'] = 'rebla',
		['price'] = 5000,
		['category'] = 'BClass',
		['hash'] = `rebla`,
		['shop'] = '',
     },
     ['dubsta2'] = {							
		['name'] = 'Dubsta',
		['brand'] = 'Tibus',
		['model'] = 'dubsta2',
		['price'] = 5000,
		['category'] = 'AClass',
		['hash'] = `dubsta`,
		['shop'] = '',
     },
     ['gburrito'] = {							
		['name'] = 'Lost Gang Burrito',
		['brand'] = 'Tibus',
		['model'] = 'gburrito',
		['price'] = 5000,
		['category'] = 'DClass',
		['hash'] = `gburrito`,
		['shop'] = '',
     },
     ['slamvan2'] = {							
		['name'] = 'Lost Slamvan',
		['brand'] = 'Tibus',
		['model'] = 'slamvan2',
		['price'] = 5000,
		['category'] = 'DClass',
		['hash'] = `slamvan2`,
		['shop'] = '',
     },
    
     ['peyote'] = {							
		['name'] = 'Peyote4',
		['brand'] = 'Tibus',
		['model'] = 'peyote',
		['price'] = 5000,
		['category'] = 'DClass',
		['hash'] = `peyote`,
		['shop'] = '',
     },
     ['tornado3'] = {							
		['name'] = 'Tornado (Gang)',
		['brand'] = 'Tibus',
		['model'] = 'tornado3',
		['price'] = 5000,
		['category'] = 'DClass',
		['hash'] = `tornado3`,
		['shop'] = '',
     },
     ['peyote2'] = {							
		['name'] = 'Peyote Gasser',
		['brand'] = 'Tibus',
		['model'] = 'peyote2',
		['price'] = 5000,
		['category'] = 'CClass',
		['hash'] = `peyote2`,
		['shop'] = '',
     },
     ['zion3'] = {							
		['name'] = 'Zion Classic',
		['brand'] = 'Tibus',
		['model'] = 'zion3',
		['price'] = 5000,
		['category'] = 'CClass',
		['hash'] = `zion3`,
		['shop'] = '',
     },
     ['jugular'] = {							
		['name'] = 'Jugular',
		['brand'] = 'Tibus',
		['model'] = 'jugular',
		['price'] = 5000,
		['category'] = 'BClass',
		['hash'] = `jugular`,
		['shop'] = '',
     },
     ['krieger'] = {							
		['name'] = 'Krieger',
		['brand'] = 'Tibus',
		['model'] = 'krieger',
		['price'] = 5000,
		['category'] = 'XClass',
		['hash'] = `krieger`,
		['shop'] = '',
     },
     ['locust'] = {							
		['name'] = 'Locust',
		['brand'] = 'Tibus',
		['model'] = 'locust',
		['price'] = 5000,
		['category'] = 'SClass',
		['hash'] = `locust`,
		['shop'] = '',
     },
     ['s80'] = {							
		['name'] = 'S80RR',
		['brand'] = 'Tibus',
		['model'] = 's80',
		['price'] = 5000,
		['category'] = 'SClass',
		['hash'] = `s80`,
		['shop'] = '',
     },
     ['gauntlet3'] = {							
		['name'] = 'Gauntlet Classic',
		['brand'] = 'Tibus',
		['model'] = 'gauntlet3',
		['price'] = 5000,
		['category'] = 'CClass',
		['hash'] = `gauntlet3`,
		['shop'] = '',
     },
     ['paragon'] = {							
		['name'] = 'Paragon R',
		['brand'] = 'Tibus',
		['model'] = 'paragon',
		['price'] = 5000,
		['category'] = 'AClass',
		['hash'] = `paragon`,
		['shop'] = '',
     },
     ['paragon2'] = {							
		['name'] = 'Paragon Armored',
		['brand'] = 'Tibus',
		['model'] = 'paragon2',
		['price'] = 5000,
		['category'] = 'AClass',
		['hash'] = `paragon2`,
		['shop'] = '',
     },
     ['deviant'] = {							
		['name'] = 'Deviant',
		['brand'] = 'Tibus',
		['model'] = 'deviant',
		['price'] = 5000,
		['category'] = 'CClass',
		['hash'] = `deviant`,
		['shop'] = '',
     },
     ['tulip'] = {							
		['name'] = 'Tulip',
		['brand'] = 'Tibus',
		['model'] = 'tulip',
		['price'] = 5000,
		['category'] = 'CClass',
		['hash'] = `tulip`,
		['shop'] = '',
     },
     ['toros'] = {							
		['name'] = 'Toros',
		['brand'] = 'Tibus',
		['model'] = 'toros',
		['price'] = 5000,
		['category'] = 'AClass',
		['hash'] = `toros`,
		['shop'] = '',
     },
     ['impaler'] = {							
		['name'] = 'Impaler',
		['brand'] = 'Tibus',
		['model'] = 'impaler',
		['price'] = 5000,
		['category'] = 'BClass',
		['hash'] = `impaler`,
		['shop'] = '',
     },
     ['swinger'] = {							
		['name'] = 'Swinger',
		['brand'] = 'Tibus',
		['model'] = 'swinger',
		['price'] = 5000,
		['category'] = 'SClass',
		['hash'] = `swinger`,
		['shop'] = '',
     },
     ['tezeract'] = {							
		['name'] = 'Tezeract',
		['brand'] = 'Tibus',
		['model'] = 'tezeract',
		['price'] = 5000,
		['category'] = 'XClass',
		['hash'] = `tezeract`,
		['shop'] = '',
     },
     ['ellie'] = {							
		['name'] = 'Ellie',
		['brand'] = 'Tibus',
		['model'] = 'ellie',
		['price'] = 5000,
		['category'] = 'AClass',
		['hash'] = `ellie`,
		['shop'] = '',
     },
     ['hotring'] = {							
		['name'] = 'Hotring Sabre',
		['brand'] = 'Tibus',
		['model'] = 'hotring',
		['price'] = 5000,
		['category'] = 'AClass',
		['hash'] = `hotring`,
		['shop'] = '',
     },
     ['comet5'] = {							
		['name'] = 'Comet SR',
		['brand'] = 'Tibus',
		['model'] = 'comet5',
		['price'] = 5000,
		['category'] = 'SClass',
		['hash'] = `comet5`,
		['shop'] = '',
     },
     ['z190'] = {							
		['name'] = '190z',
		['brand'] = 'Tibus',
		['model'] = 'z190',
		['price'] = 5000,
		['category'] = 'BClass',
		['hash'] = `z190`,
		['shop'] = '',
     },
     ['hustler'] = {							
		['name'] = 'Hustler',
		['brand'] = 'Tibus',
		['model'] = 'hustler',
		['price'] = 5000,
		['category'] = 'CClass',
		['hash'] = `hustler`,
		['shop'] = '',
     },
     ['revolter'] = {							
		['name'] = 'Revolter',
		['brand'] = 'Tibus',
		['model'] = 'revolter',
		['price'] = 5000,
		['category'] = 'AClass',
		['hash'] = `revolter`,
		['shop'] = '',
     },
     ['viseris'] = {							
		['name'] = 'Viseris',
		['brand'] = 'Tibus',
		['model'] = 'viseris',
		['price'] = 5000,
		['category'] = 'AClass',
		['hash'] = `viseris`,
		['shop'] = '',
     },
     ['autarch'] = {							
		['name'] = 'Autarch',
		['brand'] = 'Tibus',
		['model'] = 'autarch',
		['price'] = 5000,
		['category'] = 'SClass',
		['hash'] = `autarch`,
		['shop'] = '',
     },
     ['hermes'] = {							
		['name'] = 'Hermes',
		['brand'] = 'Tibus',
		['model'] = 'hermes',
		['price'] = 5000,
		['category'] = 'BClass',
		['hash'] = `hermes`,
		['shop'] = '',
     },
     ['streiter'] = {							
		['name'] = 'Streiter',
		['brand'] = 'Tibus',
		['model'] = 'streiter',
		['price'] = 5000,
		['category'] = 'BClass',
		['hash'] = `streiter`,
		['shop'] = '',
     },
     ['sentinel3'] = {							
		['name'] = 'Sentinel Classic',
		['brand'] = 'Tibus',
		['model'] = 'sentinel3',
		['price'] = 5000,
		['category'] = 'BClass',
		['hash'] = `sentinel3`,
		['shop'] = '',
     },
     ['stromberg'] = {							
		['name'] = 'Stromberg',
		['brand'] = 'Tibus',
		['model'] = 'stromberg',
		['price'] = 5000,
		['category'] = 'SClass',
		['hash'] = `stromberg`,
		['shop'] = '',
     },
     ['raiden'] = {							
		['name'] = 'Raiden',
		['brand'] = 'Tibus',
		['model'] = 'raiden',
		['price'] = 5000,
		['category'] = 'AClass',
		['hash'] = `raiden`,
		['shop'] = '',
     },
     ['comet4'] = {							
		['name'] = 'Comet Safari',
		['brand'] = 'Tibus',
		['model'] = 'comet4',
		['price'] = 5000,
		['category'] = 'AClass',
		['hash'] = `comet4`,
		['shop'] = '',
     },
     ['yosemite'] = {							
		['name'] = 'Yosemite',
		['brand'] = 'Tibus',
		['model'] = 'yosemite',
		['price'] = 5000,
		['category'] = 'CClass',
		['hash'] = `yosemite`,
		['shop'] = '',
     },
     ['riata'] = {							
		['name'] = 'Riata',
		['brand'] = 'Tibus',
		['model'] = 'riata',
		['price'] = 5000,
		['category'] = 'BClass',
		['hash'] = `riata`,
		['shop'] = '',
     },
     ['vigilante'] = {							
		['name'] = 'Vigilante',
		['brand'] = 'Tibus',
		['model'] = 'vigilante',
		['price'] = 5000,
		['category'] = 'ZClass',
		['hash'] = `vigilante`,
		['shop'] = '',
     },
     ['camper'] = {							
		['name'] = 'Camper',
		['brand'] = 'Tibus',
		['model'] = 'camper',
		['price'] = 5000,
		['category'] = 'DClass',
		['hash'] = `camper`,
		['shop'] = '',
     },
     ['xls'] = {							
		['name'] = 'XLS',
		['brand'] = 'Tibus',
		['model'] = 'xls',
		['price'] = 5000,
		['category'] = 'BClass',
		['hash'] = `xls`,
		['shop'] = '',
     },
     ['serrano'] = {							
		['name'] = 'Serrano',
		['brand'] = 'Tibus',
		['model'] = 'serrano',
		['price'] = 5000,
		['category'] = 'CClass',
		['hash'] = `serrano`,
		['shop'] = '',
     },
     ['seminole'] = {							
		['name'] = 'Seminole',
		['brand'] = 'Tibus',
		['model'] = 'seminole',
		['price'] = 5000,
		['category'] = 'CClass',
		['hash'] = `seminole`,
		['shop'] = '',
     },
     ['rocoto'] = {							
		['name'] = 'Rocoto',
		['brand'] = 'Tibus',
		['model'] = 'rocoto',
		['price'] = 5000,
		['category'] = 'CClass',
		['hash'] = `rocoto`,
		['shop'] = '',
     },
     ['huntley'] = {							
		['name'] = 'Huntley S',
		['brand'] = 'Tibus',
		['model'] = 'huntley',
		['price'] = 5000,
		['category'] = 'AClass',
		['hash'] = `huntley`,
		['shop'] = '',
     },
     ['fq2'] = {							
		['name'] = 'FQ 2',
		['brand'] = 'Tibus',
		['model'] = 'fq2',
		['price'] = 5000,
		['category'] = 'BClass',
		['hash'] = `fq2`,
		['shop'] = '',
     },
     ['dubsta'] = {							
		['name'] = 'Dubsta',
		['brand'] = 'Tibus',
		['model'] = 'dubsta',
		['price'] = 5000,
		['category'] = 'CClass',
		['hash'] = `dubsta`,
		['shop'] = '',
     },
     ['contender'] = {							
		['name'] = 'Contender',
		['brand'] = 'Tibus',
		['model'] = 'contender',
		['price'] = 5000,
		['category'] = 'BClass',
		['hash'] = `contender`,
		['shop'] = '',
     },
     ['baller6'] = {							
		['name'] = 'BallerLEArmored',
		['brand'] = 'Tibus',
		['model'] = 'baller6',
		['price'] = 5000,
		['category'] = 'BClass',
		['hash'] = `baller6`,
		['shop'] = '',
     },
     ['tornado2'] = {							
		['name'] = 'Tornado',
		['brand'] = 'Tibus',
		['model'] = 'tornado2',
		['price'] = 5000,
		['category'] = 'DClass',
		['hash'] = `tornado2`,
		['shop'] = '',
     },
     ['baller4'] = {							
		['name'] = 'BallerLELWB',
		['brand'] = 'Tibus',
		['model'] = 'baller4',
		['price'] = 5000,
		['category'] = 'BClass',
		['hash'] = `baller4`,
		['shop'] = '',
     },
     ['baller5'] = {							
		['name'] = 'BallerLArmored',
		['brand'] = 'Tibus',
		['model'] = 'baller5',
		['price'] = 5000,
		['category'] = 'BClass',
		['hash'] = `baller5`,
		['shop'] = '',
     },
     ['ztype'] = {							
		['name'] = 'Z-Type',
		['brand'] = 'Tibus',
		['model'] = 'ztype',
		['price'] = 5000,
		['category'] = 'AClass',
		['hash'] = `ztype`,
		['shop'] = '',
     },
     ['mamba'] = {							
		['name'] = 'mamba',
		['brand'] = 'Tibus',
		['model'] = 'mamba',
		['price'] = 5000,
		['category'] = 'AClass',
		['hash'] = `mamba`,
		['shop'] = '',
     },
     ['verlierer2'] = {							
		['name'] = 'Verlierer',
		['brand'] = 'Tibus',
		['model'] = 'verlierer2',
		['price'] = 5000,
		['category'] = 'BClass',
		['hash'] = `verlierer2`,
		['shop'] = '',
     },
     ['cheeta2'] = {							
		['name'] = 'Cheeta Classic',
		['brand'] = 'Tibus',
		['model'] = 'cheeta2',
		['price'] = 5000,
		['category'] = 'AClass',
		['hash'] = `cheeta2`,
		['shop'] = '',
     },
     ['jester'] = {							
		['name'] = 'Jester',
		['brand'] = 'Tibus',
		['model'] = 'jester',
		['price'] = 5000,
		['category'] = 'AClass',
		['hash'] = `jester`,
		['shop'] = '',
     },
     ['schafter3'] = {							
		['name'] = 'Schafter V12',
		['brand'] = 'Tibus',
		['model'] = 'schafter3',
		['price'] = 5000,
		['category'] = 'AClass',
		['hash'] = `schafter3`,
		['shop'] = '',
     },
     ['tampa2'] = {							
		['name'] = 'Drift Tampa',
		['brand'] = 'Tibus',
		['model'] = 'tampa2',
		['price'] = 5000,
		['category'] = 'BClass',
		['hash'] = `tampa2`,
		['shop'] = '',
     },
     ['specter2'] = {							
		['name'] = 'Specter Custom',
		['brand'] = 'Tibus',
		['model'] = 'specter2',
		['price'] = 5000,
		['category'] = 'AClass',
		['hash'] = `specter2`,
		['shop'] = '',
     },
	 ['sultan'] = {							
		['name'] = 'Sultan',
		['brand'] = 'Tibus',
		['model'] = 'sultan',
		['price'] = 5000,
		['category'] = 'CClass',
		['hash'] = `sultan`,
		['shop'] = '',
     },

	 --police
	 ['code3bmw'] = {							
		['name'] = 'Moto1',
		['brand'] = 'LSPD',
		['model'] = 'code3bmw',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `code3bmw`,
		['shop'] = '',
     },
	 ['code3boat'] = {							
		['name'] = 'Boat',
		['brand'] = 'LSPD',
		['model'] = 'code3boat',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `code3boat`,
		['shop'] = '',
     },
	 ['code3camero'] = {							
		['name'] = 'Camaro',
		['brand'] = 'LSPD',
		['model'] = 'code3camero',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `code3camero`,
		['shop'] = '',
     },
	 ['code3cap'] = {							
		['name'] = 'Caprice',
		['brand'] = 'LSPD',
		['model'] = 'code3cap',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `code3cap`,
		['shop'] = '',
     },
	 ['code3cvpi'] = {							
		['name'] = 'CVPI',
		['brand'] = 'LSPD',
		['model'] = 'code3cvpi',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `code3cvpi`,
		['shop'] = '',
     },
	 ['code3durango'] = {							
		['name'] = 'Durango',
		['brand'] = 'LSPD',
		['model'] = 'code3durango',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `code3durango`,
		['shop'] = '',
     },
	 ['code3f150'] = {							
		['name'] = 'F150',
		['brand'] = 'LSPD',
		['model'] = 'code3f150',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `code3f150`,
		['shop'] = '',
     },
	 ['code3f250'] = {							
		['name'] = 'F250',
		['brand'] = 'LSPD',
		['model'] = 'code3f250',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `code3f250`,
		['shop'] = '',
     },
	 ['code3fpis'] = {							
		['name'] = 'Taurus',
		['brand'] = 'LSPD',
		['model'] = 'code3fpis',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `code3fpis`,
		['shop'] = '',
     },
	 ['code3gator'] = {							
		['name'] = 'Gator',
		['brand'] = 'LSPD',
		['model'] = 'code3gator',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `code3gator`,
		['shop'] = '',
     },
	 ['code3harley'] = {							
		['name'] = 'Moto1',
		['brand'] = 'LSPD',
		['model'] = 'code3harley',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `code3harley`,
		['shop'] = '',
     },
	 ['code3mustang'] = {							
		['name'] = 'Mustang',
		['brand'] = 'LSPD',
		['model'] = 'code3mustang',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `code3mustang`,
		['shop'] = '',
     },
	 ['code3ram'] = {							
		['name'] = 'RAM',
		['brand'] = 'LSPD',
		['model'] = 'code3ram',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `code3ram`,
		['shop'] = '',
     },
	 ['code3silverado'] = {							
		['name'] = 'Silverado',
		['brand'] = 'LSPD',
		['model'] = 'code3silverado',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `code3silverado`,
		['shop'] = '',
     },
	 ['code310charg'] = {							
		['name'] = 'Charger',
		['brand'] = 'LSPD',
		['model'] = 'code310charg',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `code310charg`,
		['shop'] = '',
     },
	 ['code314charg'] = {							
		['name'] = 'Charger',
		['brand'] = 'LSPD',
		['model'] = 'code314charg',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `code314charg`,
		['shop'] = '',
     },
	 ['code314tahoe'] = {							
		['name'] = 'Tahoe',
		['brand'] = 'LSPD',
		['model'] = 'code314tahoe',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `code314tahoe`,
		['shop'] = '',
     },
	 ['code316fpiu'] = {							
		['name'] = 'Explorer',
		['brand'] = 'LSPD',
		['model'] = 'code316fpiu',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `code316fpiu`,
		['shop'] = '',
     },
	 ['code318charg'] = {							
		['name'] = 'Charger',
		['brand'] = 'LSPD',
		['model'] = 'code318charg',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `code318charg`,
		['shop'] = '',
     },
	 ['code318chargk9'] = {							
		['name'] = 'Charger K9',
		['brand'] = 'LSPD',
		['model'] = 'code318chargk9',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `code318chargk9`,
		['shop'] = '',
     },
	 ['code318tahoe'] = {							
		['name'] = 'Tahoe',
		['brand'] = 'LSPD',
		['model'] = 'code318tahoe',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `code318tahoe`,
		['shop'] = '',
     },
	 ['code318tahoek9'] = {							
		['name'] = 'Tahoe K9',
		['brand'] = 'LSPD',
		['model'] = 'code318tahoek9',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `code318tahoek9`,
		['shop'] = '',
     },
	 ['code319silv'] = {							
		['name'] = 'Silverado',
		['brand'] = 'LSPD',
		['model'] = 'code319silv',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `code319silv`,
		['shop'] = '',
     },
	 ['code320exp'] = {							
		['name'] = 'Explorer',
		['brand'] = 'LSPD',
		['model'] = 'code320exp',
		['price'] = 5000,
		['category'] = 'police',
		['hash'] = `code320exp`,
		['shop'] = '',
     },
}

for _, v in pairs(QBShared.Vehicles) do
	QBShared.VehicleHashes[v.hash] = v
end
